;;; rxrs-tests.scm -- R7RS section-by-section conformance tests.
;;; Evaluates representative expressions from each R7RS section and VERIFIES each
;;; result against its expected value (no longer a bare load-only smoke test).
;;; Copyright 2026 by Frobenius Norm LLC 2026-06-23 00:00:00
;;; Free for non-commercial use. Commercial use requires a license.
;;;
;;; Exposes top-level counters  rxrs-pass / rxrs-fail  for conform-runner.scm.
;;;
;;; chk: (chk id expected expr) -- evaluates expr (guarded), compares with equal?,
;;; bumps rxrs-pass / rxrs-fail, and on failure prints "  FAIL id: expected E got G".
;;; chk~: tolerant numeric compare for inexact results.
;;; cwv: collects a multiple-values result into a list for comparison.
;;;
;;; A handful of checks below encode the R7RS-correct value for cases where this
;;; build currently DIVERGES (assoc/comparator, exact rationalize, complex nan?/
;;; integer?, non-ASCII digit-value).  They are left to FAIL VISIBLY and are tracked
;;; in proposal_bug_registry_P88.md -- per policy, never skipped or marked xfail.

(define rxrs-pass 0)
(define rxrs-fail 0)
;; No known nonconformances here -- rxrs failures are real bugs (registered), never exceptions.
(define rxrs-exception 0)
(define rxrs-exception-expected 0)

;; FAIL lines carry the CHALLENGE form in the harness-parseable shape shared with the other
;; suites ("FAIL <id> | expr <form> | expected <e> | got <g>"), so the report's failures table can
;; show the expression that was evaluated rather than just an id.  The form has to be threaded in
;; from the `chk` macro: rxrs-check only ever sees a thunk.
(define (rxrs-fail! id expected got form)
  (set! rxrs-fail (+ rxrs-fail 1))
  (display "  FAIL ") (display id) (display " | expr ") (write form)
  (display " | expected ") (write expected)
  (display " | got ") (write got) (newline))

(define (rxrs-check id expected thunk30 form)
  (guard (e (#t (rxrs-fail! id expected 'exception form)))
    (let ((got (thunk30)))
      (if (equal? got expected)
          (set! rxrs-pass (+ rxrs-pass 1))
          (rxrs-fail! id expected got form)))))

(define-syntax chk
  (syntax-rules () ((chk id expected expr) (rxrs-check id expected (lambda () expr) (quote expr)))))

;; tolerant inexact compare (|got-expected| < tol)
(define (rxrs-check~ id expected tol thunk31 form)
  (guard (e (#t (rxrs-fail! id expected 'exception form)))
    (let ((got (thunk31)))
      (if (and (number? got) (< (abs (- got expected)) tol))
          (set! rxrs-pass (+ rxrs-pass 1))
          (rxrs-fail! id expected got form)))))
(define-syntax chk~
  (syntax-rules ()
    ((chk~ id expected tol expr) (rxrs-check~ id expected tol (lambda () expr) (quote expr)))))

;; collect a multiple-values producer into a list
(define-syntax cwv
  (syntax-rules () ((cwv expr) (call-with-values (lambda () expr) list))))

;; write-to-string: capture (write x) output -- exercises the PRINTER directly.
;; Several conformance bugs lived only in written form (invisible to value=value
;; checks): vector "#vector(...)" , bytevector "#bytevector(...)" , inexact reals
;; printed with no decimal point, and control chars as #\xNN instead of R7RS names.
(define (w->s x) (let ((p (open-output-string))) (write x p) (get-output-string p)))

(news ";;;4.1.1 Variable references\n")
(define x 28)
(chk "4.1.1" 28 x)

(news ";;;4.1.2 Literal expressions\n")
(chk "4.1.2a" 'a (quote a))
(chk "4.1.2b" '#(a b c) (quote #(a b c)))
(chk "4.1.2c" '(+ 1 2) (quote (+ 1 2)))
(chk "4.1.2d" 'a 'a)
(chk "4.1.2e" '#(a b c) '#(a b c))
(chk "4.1.2f" '(+ 1 2) '(+ 1 2))
(chk "4.1.2g" '(quote a) '(quote a))
(chk "4.1.2h" '(quote a) ''a)
(chk "4.1.2i" "abc" '"abc")
(chk "4.1.2j" "abc" "abc")
(chk "4.1.2k" 145932 '145932)
(chk "4.1.2l" 145932 145932)
(chk "4.1.2m" #t '#t)
(chk "4.1.2n" #t #t)

(news ";;;4.1.3 Procedure calls\n")
(chk "4.1.3a" 7 (+ 3 4))
(chk "4.1.3b" 12 ((if #f + *) 3 4))

(news ";;;4.1.4 Procedures\n")
(chk "4.1.4a" 8 ((lambda (x) (+ x x)) 4))
(define reverse-subtract (lambda (x y) (- y x)))
(chk "4.1.4b" 3 (reverse-subtract 7 10))
(define add4 (let ((x 4)) (lambda (y) (+ x y))))
(chk "4.1.4c" 10 (add4 6))
(chk "4.1.4d" '(3 4 4 6) ((lambda x x) 3 4 4 6))
(chk "4.1.4e" '(5 6) ((lambda (x y . z) z) 3 4 5 6))

(news ";;;4.1.5 Conditionals\n")
(chk "4.1.5a" 'yes (if (> 3 2) 'yes 'no))
(chk "4.1.5b" 'no (if (> 2 3) 'yes 'no))
(chk "4.1.5c" 1 (if (> 3 2) (- 3 2) (+ 3 2)))

(news ";;;4.1.6 Assignments\n")
(define x 2)
(chk "4.1.6a" 3 (+ x 1))
(set! x 4)
(chk "4.1.6b" 5 (+ x 1))

(news ";;;4.1.7 include\n")
;; include of a missing file is handled gracefully (logs, no crash); just confirm survival.
(chk "4.1.7" 'ok (begin (guard (e (#t #t)) (load "dummy.scm")) 'ok))

(news ";;;4.2.1 Conditionals\n")
(chk "4.2.1a" 'greater (cond ((> 3 2) 'greater) ((< 3 2) 'less)))
(chk "4.2.1b" 'greater (cond ((> 3 2) 'greater) ((< 3 2) 'less) (else 'equal)))
(chk "4.2.1c" 2 (cond ((assv 'b '((a 1) (b 2))) => cadr) (else #f)))
(chk "4.2.1d" 'composite (case (* 2 3) ((2 3 5 7) 'prime) ((1 4 6 8 9) 'composite)))
(chk "4.2.1e" 'c (case (car '(c d)) ((a e i o u) 'vowel) ((w y) 'semivowel) (else => (lambda (x) x))))
(chk "4.2.1f" #t (and (= 2 2) (> 2 1)))
(chk "4.2.1g" #f (and (= 2 2) (< 2 1)))
(chk "4.2.1h" '(f g) (and 1 2 'c '(f g)))
(chk "4.2.1i" #t (and))
(chk "4.2.1j" #t (or (= 2 2) (> 2 1)))
(chk "4.2.1k" #t (or (= 2 2) (< 2 1)))
(chk "4.2.1l" #f (or #f #f #f))
(chk "4.2.1m" '(b c) (or (memq 'b '(a b c)) (/ 3 0)))
(chk "4.2.1n" 'yes (let ((r 'no)) (when (= 1 1.0) (set! r 'yes)) r))
(chk "4.2.1o" 'no  (let ((r 'no)) (unless (= 1 1.0) (set! r 'yes)) r))

(news ";;;4.2.2 Binding constructs\n")
(chk "4.2.2a" 6 (let ((x 2) (y 3)) (* x y)))
(chk "4.2.2b" 35 (let ((x 2) (y 3)) (let ((x 7) (z (+ x y))) (* z x))))
(chk "4.2.2c" 70 (let ((x 2) (y 3)) (let* ((x 7) (z (+ x y))) (* z x))))
(chk "4.2.2d" #t (letrec ((even? (lambda (n) (if (zero? n) #t (odd? (- n 1)))))
                          (odd?  (lambda (n) (if (zero? n) #f (even? (- n 1))))))
                  (even? 88)))
(chk "4.2.2e" 5 (letrec* ((p (lambda (x) (+ 1 (q (- x 1)))))
                          (q (lambda (y) (if (zero? y) 0 (+ 1 (p (- y 1))))))
                          (x (p 5)) (y x))
                  y))

(news ";;;4.2.3 Sequencing\n")
(define x 0)
(chk "4.2.3a" 6 (and (= x 0) (begin (set! x 5) (+ x 1))))
(chk "4.2.3b" 5 (begin (display "4 plus 1 equals ") (+ 4 1)))
(newline)

(news ";;;4.2.4 Iteration\n")
(chk "4.2.4a" '#(0 1 2 3 4)
  (do ((vec (make-vector 5)) (i 0 (+ i 1))) ((= i 5) vec) (vector-set! vec i i)))
(chk "4.2.4b" 25
  (let ((x '(1 3 5 7 9))) (do ((x x (cdr x)) (sum 0 (+ sum (car x)))) ((null? x) sum))))
(chk "4.2.4c" '((6 1 3) (-5 -2))
  (let loopn ((numbers '(3 -2 1 6 -5)) (nonneg '()) (neg '()))
    (cond ((null? numbers) (list nonneg neg))
          ((>= (car numbers) 0) (loopn (cdr numbers) (cons (car numbers) nonneg) neg))
          ((< (car numbers) 0)  (loopn (cdr numbers) nonneg (cons (car numbers) neg))))))

(news ";;;4.2.5 Delayed evaluation\n")
(chk "4.2.5a" 3 (force (delay (+ 1 2))))
(chk "4.2.5b" '(3 3) (let ((p (delay (+ 1 2)))) (list (force p) (force p))))

(news ";;;4.2.6 Dynamic bindings - parameterize not exercised here (call/cc-based)\n")

(news ";;;4.2.7 Exception handling\n")
(chk "4.2.7a" 42
  (guard (condition ((assq 'a condition) => cdr) ((assq 'b condition)))
    (raise (list (cons 'a 42)))))
(chk "4.2.7b" '(b . 23)
  (guard (condition ((assq 'a condition) => cdr) ((assq 'b condition)))
    (raise (list (cons 'b 23)))))

(news ";;;4.2.8 Quasiquotation\n")
(chk "4.2.8a" '(list 3 4) `(list ,(+ 1 2) 4))
(chk "4.2.8b" '(list a (quote a)) (let ((name 'a)) `(list ,name ',name)))
(chk "4.2.8c" '(a 3 4 5 6 b) `(a ,(+ 1 2) ,@(map abs '(4 -5 6)) b))
(chk "4.2.8d" '((foo 7) . cons) `(( foo ,(- 10 3)) ,@(cdr '(c)) . ,(car '(cons))))
(chk "4.2.8e" '#(10 5 2 4 3 8) `#(10 5 ,(sqrt 4) ,@(map sqrt '(16 9)) 8))
;;; nested quasiquote (R7RS 4.2.8) -- value-checked; verified conformant 2026-08-12 (was DEBT):
(chk "4.2.8-nest-depth" '(a (quasiquote (b (unquote (+ 1 2)) (unquote (foo 4 d)) e)) f)
  `(a `(b ,(+ 1 2) ,(foo ,(+ 1 3) d) e) f))
(chk "4.2.8-nest-unquote-unquote" '(a (quasiquote (b (unquote x) (unquote (quote y)) d)) e)
  (let ((name1 'x) (name2 'y)) `(a `(b ,,name1 ,',name2 d) e)))
(chk "4.2.8f" '((1 2) 3 4 five 6) `((1 2) 3 4 five 6))
(chk "4.2.8g" '((1 2) 3 4 five 6)
  (let ((a 3)) (cons '(1 2) (cons a (cons 4 (cons 'five '(6)))))))
(chk "4.2.8h" '((1 2) 3 4 five 6) (let ((a 3)) `((1 2) ,a ,4 ,'five 6)))
(chk "4.2.8i" '((1 2) 3 4 five 6) (let ((a 3)) (list (list 1 2) a 4 'five 6)))
(chk "4.2.8j" '(list 3 4) (quasiquote (list (unquote (+ 1 2)) 4)))
(chk "4.2.8k" '(quasiquote (list (unquote (+ 1 2)) 4)) '(quasiquote (list (unquote (+ 1 2)) 4)))

(news ";;;5.3.1 Top level definitions\n")
(define add3 (lambda (x) (+ x 3)))
(chk "5.3.1a" 6 (add3 3))
(define first car)
(chk "5.3.1b" 1 (first '(1 2)))

(news ";;;5.3.2 Internal definitions\n")
(chk "5.3.2a" 45
  (let ((x 5)) (define foo (lambda (y) (bar x y))) (define bar (lambda (a b) (+ (* a b) a))) (foo (+ x 3))))
(chk "5.3.2b" 45
  (let ((x 5)) (letrec* ((foo (lambda (y) (bar x y))) (bar (lambda (a b) (+ (* a b) a)))) (foo (+ x 3)))))

(news ";;;5.3.3 Multiple values\n")
(chk "5.3.3a" '(2 1) (cwv (floor/ 5 2)))
(chk "5.3.3b" 7 (call-with-values (lambda () (values 3 4)) +))
(lamb-integrity-check)

(news ";;;5.4 Syntax definitions (define-syntax / syntax-rules)\n")
(chk "5.4a" '(2 1)
  (let ((x 1) (y 2))
    (define-syntax swp (syntax-rules () ((swp a b) (let ((tmp a)) (set! a b) (set! b tmp)))))
    (swp x y) (list x y)))

(news ";;;6.1 Equivalence predicates\n")
(chk "6.1-eqv-fg" #f
  (letrec ((f (lambda () (if (eqv? f g) 'f 'both))) (g (lambda () (if (eqv? f g) 'g 'both)))) (eqv? f g)))
(chk "6.1-eqv-aa" #t (eqv? 'a 'a))
(chk "6.1-eqv-ab" #f (eqv? 'a 'b))
(chk "6.1-eqv-22" #t (eqv? 2 2))
(chk "6.1-eqv-2-2.0" #f (eqv? 2 2.0))
(chk "6.1-eqv-nil" #t (eqv? '() '()))
(chk "6.1-eqv-big" #t (eqv? 100000000 100000000))
(chk "6.1-eqv-cons" #f (eqv? (cons 1 2) (cons 1 2)))
(chk "6.1-eqv-lam12" #f (eqv? (lambda () 1) (lambda () 2)))
(chk "6.1-eqv-pp" #t (let ((p (lambda (x) x))) (eqv? p p)))
(chk "6.1-eqv-f-nil" #f (eqv? #f 'nil))
(chk "6.1-eqv-estr" #f (eqv? "" ""))            ; impl-defined (R7RS unspecified)
(chk "6.1-eqv-evec" #f (eqv? '#() '#()))        ; impl-defined
(chk "6.1-eqv-lamx" #f (eqv? (lambda (x) x) (lambda (x) x)))
(chk "6.1-eqv-lamxy" #f (eqv? (lambda (x) x) (lambda (y) y)))
(define gen-counter (lambda () (let ((n 0)) (lambda () (set! n (+ n 1)) n))))
(chk "6.1-eqv-gc-self" #t (let ((g (gen-counter))) (eqv? g g)))
(chk "6.1-eqv-gc-2" #f (eqv? (gen-counter) (gen-counter)))
(define gen-loser (lambda () (let ((n 0)) (lambda () (set! n (+ n 1)) 27))))
(chk "6.1-eqv-gl-self" #t (let ((g (gen-loser))) (eqv? g g)))
(chk "6.1-eqv-gl-2" #f (eqv? (gen-loser) (gen-loser)))  ; impl-defined
(chk "6.1-eqv-a-list" #f (eqv? '(a) '(a)))      ; impl-defined
(chk "6.1-eqv-a-str" #f (eqv? "a" "a"))         ; impl-defined
(chk "6.1-eqv-cdr" #f (eqv? '(b) (cdr '(a b)))) ; impl-defined
(chk "6.1-eqv-xx" #t (let ((x '(a))) (eqv? x x)))
(chk "6.1-eq-aa" #t (eq? 'a 'a))
(chk "6.1-eq-alist" #f (eq? '(a) '(a)))         ; impl-defined
(chk "6.1-eq-lista" #f (eq? (list 'a) (list 'a)))
(chk "6.1-eq-astr" #f (eq? "a" "a"))            ; impl-defined
(chk "6.1-eq-estr" #f (eq? "" ""))              ; impl-defined
(chk "6.1-eq-nil" #t (eq? '() '()))
(chk "6.1-eq-22" #t (eq? 2 2))                  ; impl-defined (int eq? by value)
(chk "6.1-eq-AA" #t (eq? #\A #\A))              ; impl-defined
(chk "6.1-eq-car" #t (eq? car car))
(chk "6.1-eq-nn" #t (let ((n (+ 2 3))) (eq? n n)))
(chk "6.1-eq-xx" #t (let ((x '(a))) (eq? x x)))
(chk "6.1-eq-vv" #t (let ((x '#())) (eq? x x)))
(chk "6.1-eq-pp" #t (let ((p (lambda (x) x))) (eq? p p)))
(chk "6.1-equal-aa" #t (equal? 'a 'a))
(chk "6.1-equal-list" #t (equal? '(a) '(a)))
(chk "6.1-equal-nest" #t (equal? '(a (b) c) '(a (b) c)))
(chk "6.1-equal-str" #t (equal? "abc" "abc"))
(chk "6.1-equal-22" #t (equal? 2 2))
(chk "6.1-equal-vec" #t (equal? (make-vector 5 'a) (make-vector 5 'a)))
;;; circular equal? '#1=(a b . #1#) -- DEBT (datum labels / cyclic equal? not exercised)
(chk "6.1-equal-lam" #f (equal? (lambda (x) x) (lambda (y) y)))

(news ";;;6.2.6 Numerical operations\n")
(chk "6.2-complex-i" #t (complex? 3+4i))
(chk "6.2-complex-3" #t (complex? 3))
(chk "6.2-real-3" #t (real? 3))
(chk "6.2-real-2.5+0i" #t (real? -2.5+0i))
;;; (real? -2.5+0.0i) -- R7RS unspecified for inexact-zero imaginary; not checked
(chk "6.2-real-e1e10" #t (real? #e1e10))
(chk "6.2-real-inf" #t (real? +inf.0))
(chk "6.2-real-nan" #t (real? +nan.0))
(chk "6.2-rat-ninf" #f (rational? -inf.0))
(chk "6.2-rat-3.5" #t (rational? 3.5))
(chk "6.2-rat-6/10" #t (rational? 6/10))
(chk "6.2-rat-6/3" #t (rational? 6/3))
(chk "6.2-int-3+0i" #t (integer? 3+0i))         ; DIVERGES: build returns #f (P88)
(chk "6.2-int-3.0" #t (integer? 3.0))
(chk "6.2-int-8/4" #t (integer? 8/4))
(chk "6.2-exact-3.0" #f (exact? 3.0))
(chk "6.2-exact-e3.0" #t (exact? #e3.0))
(chk "6.2-inexact-3." #t (inexact? 3.))
(chk "6.2-eint-32" #t (exact-integer? 32))
(chk "6.2-eint-32.0" #f (exact-integer? 32.0))
(chk "6.2-eint-32/5" #f (exact-integer? 32/5))
(chk "6.2-fin-3" #t (finite? 3))
(chk "6.2-fin-inf" #f (finite? +inf.0))
(chk "6.2-fin-3+infi" #f (finite? 3.0+inf.0i))
(chk "6.2-inf-3" #f (infinite? 3))
(chk "6.2-inf-inf" #t (infinite? +inf.0))
(chk "6.2-inf-nan" #f (infinite? +nan.0))
(chk "6.2-inf-3+infi" #t (infinite? 3.0+inf.0i))
(chk "6.2-nan-nan" #t (nan? +nan.0))
(chk "6.2-nan-32" #f (nan? 32))
(chk "6.2-nan-cplx" #t (nan? +nan.0+5.0i))      ; DIVERGES: build returns #f (P88)
(chk "6.2-nan-1+2i" #f (nan? 1+2i))
(chk "6.2-max34" 4 (max 3 4))
(chk "6.2-max3.94" 4.0 (max 3.9 4))
(chk "6.2-add34" 7 (+ 3 4))
(chk "6.2-add3" 3 (+ 3))
(chk "6.2-add0" 0 (+))
(chk "6.2-mul4" 4 (* 4))
(chk "6.2-mul1" 1 (*))
(chk "6.2-sub34" -1 (- 3 4))
(chk "6.2-sub345" -6 (- 3 4 5))
(chk "6.2-sub3" -3 (- 3))
(chk "6.2-div345" 3/20 (/ 3 4 5))
(chk "6.2-div3" 1/3 (/ 3))
(chk "6.2-abs" 7 (abs -7))
(chk "6.2-floor/5_2"  '(2 1)   (cwv (floor/ 5 2)))
(chk "6.2-floor/-5_2" '(-3 1)  (cwv (floor/ -5 2)))
(chk "6.2-floor/5_-2" '(-3 -1) (cwv (floor/ 5 -2)))
(chk "6.2-floor/-5_-2" '(2 -1) (cwv (floor/ -5 -2)))
(chk "6.2-trunc/5_2"  '(2 1)   (cwv (truncate/ 5 2)))
(chk "6.2-trunc/-5_2" '(-2 -1) (cwv (truncate/ -5 2)))
(chk "6.2-trunc/5_-2" '(-2 1)  (cwv (truncate/ 5 -2)))
(chk "6.2-trunc/-5_-2" '(2 -1) (cwv (truncate/ -5 -2)))
(chk "6.2-trunc/-5.0_-2" '(2.0 -1.0) (cwv (truncate/ -5.0 -2)))
(chk "6.2-gcd" 4 (gcd 32 -36))
(chk "6.2-gcd0" 0 (gcd))
(chk "6.2-lcm" 288 (lcm 32 -36))
(chk "6.2-lcm-inx" 288.0 (lcm 32.0 -36))
(chk "6.2-lcm1" 1 (lcm))
(chk "6.2-numer" 3 (numerator (/ 6 4)))
(chk "6.2-denom" 2 (denominator (/ 6 4)))
(chk~ "6.2-denom-inx" 2.0 1e-9 (denominator (inexact (/ 6 4))))  ; inexact 2.0 (tolerant: f32/f64 repr)
(chk "6.2-floor-4.3" -5.0 (floor -4.3))
(chk "6.2-ceil-4.3" -4.0 (ceiling -4.3))
(chk "6.2-trunc-4.3" -4.0 (truncate -4.3))
(chk "6.2-round-4.3" -4.0 (round -4.3))
(chk "6.2-floor3.5" 3.0 (floor 3.5))
(chk "6.2-ceil3.5" 4.0 (ceiling 3.5))
(chk "6.2-trunc3.5" 3.0 (truncate 3.5))
(chk "6.2-round3.5" 4.0 (round 3.5))
(chk "6.2-round7/2" 4 (round 7/2))
(chk "6.2-round7" 7 (round 7))
(chk "6.2-ratlize-ex" 1/3 (rationalize (exact .3) 1/10))  ; DIVERGES: build returns 1.5 (P88)
(chk~ "6.2-ratlize-inx" 0.3333333 1e-5 (rationalize .3 1/10))
(chk "6.2-square42" 1764 (square 42))
(chk "6.2-square2.0" 4.0 (square 2.0))
(chk "6.2-sqrt9" 3 (sqrt 9))
(chk "6.2-sqrt-1" 0+1i (sqrt -1))
(chk "6.2-eisqrt4" '(2 0) (cwv (exact-integer-sqrt 4)))
(chk "6.2-eisqrt5" '(2 1) (cwv (exact-integer-sqrt 5)))
(chk "6.2-s2n100" 100 (string->number "100"))
(chk "6.2-s2n100-16" 256 (string->number "100" 16))
(chk "6.2-s2n1e2" 100.0 (string->number "1e2"))
;;; string->number rationals + #b/#o/#d/#x radix + #e/#i exactness prefixes, either order (6.2.6)
(chk "6.2-s2n-rat"    1/2   (string->number "1/2"))
(chk "6.2-s2n-ratred" 2     (string->number "6/3"))
(chk "6.2-s2n-ratneg" -3/4  (string->number "-3/4"))
(chk "6.2-s2n-hashx"  255   (string->number "#xff"))
(chk "6.2-s2n-hashb"  5     (string->number "#b101"))
(chk "6.2-s2n-hasho"  8     (string->number "#o10"))
(chk "6.2-s2n-exact"  3     (string->number "#e3"))
(chk "6.2-s2n-inx"    16.0  (string->number "#x#i10"))
(chk "6.2-s2n-inx2"   8.0   (string->number "#i#o10"))
;;; inexact reals must WRITE with a decimal point / R7RS inf-nan tokens (7.1.1)
(chk "6.2-w-1.0"   "1.0"     (w->s 1.0))
(chk "6.2-w-neg"   "-2.5"    (w->s -2.5))
(chk "6.2-w-inf"   "+inf.0"  (w->s (/ 1.0 0.0)))
(chk "6.2-w-ninf"  "-inf.0"  (w->s (/ -1.0 0.0)))
(chk "6.2-w-nan"   "+nan.0"  (w->s (- (/ 1.0 0.0) (/ 1.0 0.0))))
;;; number->string is SIGNED in every radix (was two's-complement: -255 base16 -> ffffffffffffff01)
(chk "6.2-n2s-neghex" "-ff" (number->string -255 16))
(chk "6.2-n2s-negoct" "-10" (number->string -8 8))
(chk "6.2-n2s-poshex" "ff"  (number->string 255 16))
;;; complex WRITE form must carry real part + sign so it reads back (was "1i")
(chk "6.2-w-cpx-i"  "0+1i" (w->s (sqrt -1)))
(chk "6.2-w-cpx-34" "3-4i" (w->s (make-rectangular 3 -4)))
;;; float64 inexact prints the SHORTEST round-tripping decimal (was 0.33333333333333331);
;;; whole-valued / exponential-literal float64 still print positionally with a decimal point.
(chk "6.2-w-third" "0.3333333333333333" (w->s (exact->inexact 1/3)))
(chk "6.2-w-100"   "100.0"              (w->s (exact->inexact 100)))
;;; B11 / P70: exact bignum rationals -- expt with negative exponent returns an exact rational whose
;;; denominator is a bignum (was inexact float; general big-rational arithmetic was broken -> 1/16).
(chk "6.2-B11-exact"  #t (exact? (expt (expt 2 64) -1)))
(chk "6.2-B11-n2s"    "1/18446744073709551616" (number->string (expt (expt 2 64) -1)))
(chk "6.2-B11-num"    1 (numerator (expt (expt 2 64) -1)))
(chk "6.2-B11-den="   #t (= (denominator (expt (expt 2 64) -1)) (expt 2 64)))
(chk "6.2-B11-rt"     1 (* (expt 2 64) (expt (expt 2 64) -1)))
(chk "6.2-B11-eq"     #t (= (expt (expt 2 64) -1) (/ 1 (expt 2 64))))
(chk "6.2-P70-div16"  #t (= (* 16 (/ 1 (expt 2 64))) (/ 1 (expt 2 60))))   ; the old 1/16 bug
(chk "6.2-P70-add"    #t (= (+ (/ 1 (expt 2 64)) (/ 1 (expt 2 64))) (/ 1 (expt 2 63))))
(chk "6.2-P70-recip"  #t (= (/ 1 (/ 1 (expt 2 64))) (expt 2 64)))
(chk "6.2-P70-neg-n2s" "-1/18446744073709551616" (number->string (- (/ 1 (expt 2 64)))))
(chk "6.2-P70-reduce" 2 (/ (expt 2 65) (expt 2 64)))
(chk "6.2-P70-cmp"    #t (< (/ 1 (expt 2 65)) (/ 1 (expt 2 64))))
(chk "6.2-P70-floor"  0 (floor (/ 1 (expt 2 64))))
(chk "6.2-P70-abs"    #t (= (abs (- (/ 1 (expt 2 64)))) (/ 1 (expt 2 64))))
(chk "6.2-P70-exptbase" #t (= (expt 1/2 100) (/ 1 (expt 2 100))))
(chk "6.2-P70-small"  5/6 (+ 1/2 1/3))    ; small rationals unaffected
;;; B166: string->number and the reader parse big-rational LITERALS (bignum components)
(chk "6.2-B166-s2n"   #t (= (string->number "1/18446744073709551616") (/ 1 (expt 2 64))))
(chk "6.2-B166-n2s"   "18446744073709551617/2" (number->string (string->number "18446744073709551617/2")))
(chk "6.2-B166-reduce" 2 (string->number "36893488147419103232/18446744073709551616"))
(chk "6.2-B166-zerod" #f (string->number "1/0"))
(chk "6.2-B166-rdlit" #t (= 1/18446744073709551616 (expt (expt 2 64) -1)))    ; source literal reads back

(news ";;;6.3 Booleans\n")
(chk "6.3a" #f (not #t))
(chk "6.3b" #f (not 3))
(chk "6.3c" #f (not (list 3)))
(chk "6.3d" #t (not #f))
(chk "6.3e" #f (not '()))
(chk "6.3f" #f (not (list)))
(chk "6.3g" #f (not 'nil))
(chk "6.3h" #t (boolean? #f))
(chk "6.3i" #f (boolean? 0))
(chk "6.3j" #f (boolean? '()))

(news ";;;6.4 Pairs and lists\n")
(define lx (list 'a 'b 'c))
(define ly lx)
(chk "6.4-y" '(a b c) ly)
(chk "6.4-listy" #t (list? ly))
(set-cdr! lx 4)
(chk "6.4-x-mut" '(a . 4) lx)
(chk "6.4-eqv-xy" #t (eqv? lx ly))
(chk "6.4-listy2" #f (list? ly))
(set-cdr! lx lx)
(chk "6.4-list-cyc" #f (list? lx))
(chk "6.4-pair-dot" #t (pair? '(a . b)))
(chk "6.4-pair-list" #t (pair? '(a b c)))
(chk "6.4-pair-nil" #f (pair? '()))
(chk "6.4-pair-vec" #f (pair? '#(a b)))
(chk "6.4-cons1" '(a) (cons 'a '()))
(chk "6.4-cons2" '((a) b c d) (cons '(a) '(b c d)))
(chk "6.4-cons3" '("a" b c) (cons "a" '(b c)))
(chk "6.4-cons4" '(a . 3) (cons 'a 3))
(chk "6.4-cons5" '((a b) . c) (cons '(a b) 'c))
(chk "6.4-car1" 'a (car '(a b c)))
(chk "6.4-car2" '(a) (car '((a) b c d)))
(chk "6.4-car3" 1 (car '(1 . 2)))
(chk "6.4-car-nil" #f (guard (exn (#t #f)) (car '())))
(chk "6.4-cdr1" '(b c d) (cdr '((a) b c d)))
(chk "6.4-cdr2" 2 (cdr '(1 . 2)))
(chk "6.4-cdr-nil" #f (guard (exn (#t #f)) (cdr '())))
(chk "6.4-listp1" #t (list? '(a b c)))
(chk "6.4-list-nil" '(()) (list '()))
(chk "6.4-listp2" #f (list? '(a . b)))
(chk "6.4-list-cyc2" #f (let ((x (list 'a))) (set-cdr! x x) (list? x)))
(chk "6.4-list3" '(a 7 c) (list 'a (+ 3 4) 'c))
(chk "6.4-list0" '() (list))
(chk "6.4-len3" 3 (length '(a b c)))
(chk "6.4-len3b" 3 (length '(a (b) (c d e))))
(chk "6.4-len0" 0 (length '()))
(chk "6.4-app1" '(x y) (append '(x) '(y)))
(chk "6.4-app2" '(a b c d) (append '(a) '(b c d)))
(chk "6.4-app3" '(a (b) (c)) (append '(a (b)) '((c))))
(chk "6.4-app4" '(a b c . d) (append '(a b) '(c . d)))
(chk "6.4-app5" 'a (append '() 'a))
(chk "6.4-rev1" '(c b a) (reverse '(a b c)))
(chk "6.4-rev2" '((e (f)) d (b c) a) (reverse '(a (b c) d (e (f)))))
(chk "6.4-lref" 'c (list-ref '(a b c d) 2))
(chk "6.4-lref2" 'c (list-ref '(a b c d) (exact (round 1.8))))
(chk "6.4-lset" '(one two three)
  (let ((ls (list 'one 'two 'five!))) (list-set! ls 2 'three) ls))
(chk "6.4-memq1" '(a b c) (memq 'a '(a b c)))
(chk "6.4-memq2" '(b c) (memq 'b '(a b c)))
(chk "6.4-memq3" #f (memq 'a '(b c d)))
(chk "6.4-memq4" #f (memq (list 'a) '(b (a) c)))
(chk "6.4-member1" '((a) c) (member (list 'a) '(b (a) c)))
(chk "6.4-member2" '("b" "c") (member "B" '("a" "b" "c") string-ci=?))
(chk "6.4-memq101" '(101 102) (memq 101 '(100 101 102)))
(chk "6.4-memv101" '(101 102) (memv 101 '(100 101 102)))
(define alist '((a 1) (b 2) (c 3)))
(chk "6.4-assq-a" '(a 1) (assq 'a alist))
(chk "6.4-assq-b" '(b 2) (assq 'b alist))
(chk "6.4-assq-d" #f (assq 'd alist))
(chk "6.4-assq-la" #f (assq (list 'a) '(((a)) ((b)) ((c)))))
(chk "6.4-assoc-la" '((a)) (assoc (list 'a) '(((a)) ((b)) ((c)))))
(chk "6.4-assoc-2.0" '(2 4) (assoc 2.0 '((1 1) (2 4) (3 9)) =))  ; DIVERGES: build returns #f (P88)
(chk "6.4-assq-5" '(5 7) (assq 5 '((2 3) (5 7) (11 13))))
(chk "6.4-assv-5" '(5 7) (assv 5 '((2 3) (5 7) (11 13))))
(define la '(1 8 2 8))
(define lb (list-copy la))
(set-car! lb 3)
(chk "6.4-lcopy-b" '(3 8 2 8) lb)
(chk "6.4-lcopy-a" '(1 8 2 8) la)

(news ";;;6.5 Symbols\n")
(chk "6.5-sym-foo" #t (symbol? 'foo))
(chk "6.5-sym-car" #t (symbol? (car '(a b))))
(chk "6.5-sym-str" #f (symbol? "bar"))
(chk "6.5-sym-nil" #t (symbol? 'nil))
(chk "6.5-sym-emptylist" #f (symbol? '()))
(chk "6.5-sym-f" #f (symbol? #f))
(chk "6.5-s2s-fish" "flying-fish" (symbol->string 'flying-fish))
(chk "6.5-s2s-Martin" "Martin" (symbol->string 'Martin))
(chk "6.5-s2s-Malvina" "Malvina" (symbol->string (string->symbol "Malvina")))
(chk "6.5-eqv-bitBlt" #t (eqv? 'bitBlt (string->symbol "bitBlt")))
(chk "6.5-eqv-Lolly" #t (eqv? 'LollyPop (string->symbol (symbol->string 'LollyPop))))
(chk "6.5-roundtrip" #t
  (string=? "K. Harper, M.D." (symbol->string (string->symbol "K. Harper, M.D."))))
;;; symbol WRITE form -- R7RS 7.1.1 |...| bars when the bare spelling would not read back
;;; (was written bare/unreadable: "hello world", empty symbol as "", "123" as a number).
(chk "6.5-w-space" "|hello world|" (w->s (string->symbol "hello world")))
(chk "6.5-w-empty" "||"            (w->s (string->symbol "")))
(chk "6.5-w-paren" "|a(b|"         (w->s (string->symbol "a(b")))
(chk "6.5-w-num"   "|123|"         (w->s (string->symbol "123")))
(chk "6.5-w-plain" "abc"           (w->s 'abc))
(chk "6.5-w-peculiar" "+"          (w->s '+))
(chk "6.5-w-arrow" "list->vector"  (w->s 'list->vector))
(chk "6.5-w-rt" #t                                            ; bar-written symbol re-reads equal
  (let ((y (string->symbol "a b|c"))) (eq? y (read (open-input-string (w->s y))))))

(news ";;;6.6 Characters\n")
(chk "6.6-dv-3" 3 (digit-value #\3))
(chk "6.6-dv-arab" 4 (digit-value #\x0664))   ; DIVERGES: non-ASCII digit-value returns #f (P88)
(chk "6.6-dv-guj" 0 (digit-value #\x0AE6))    ; DIVERGES: non-ASCII digit-value returns #f (P88)
(chk "6.6-dv-lao" #f (digit-value #\x0EA6))
;;; B162: char-alphabetic? + case ops beyond ASCII/Latin-1 (Greek, Cyrillic, CJK)
(chk "6.6-alpha-greek"    #t (char-alphabetic? (integer->char #x03BB)))   ; lambda
(chk "6.6-alpha-cyril"    #t (char-alphabetic? (integer->char #x0434)))   ; de
(chk "6.6-alpha-cjk"      #t (char-alphabetic? (integer->char #x4E2D)))   ; zhong
(chk "6.6-alpha-nonlet"   #f (char-alphabetic? #\5))
(chk "6.6-upcase-greek"   #x039B (char->integer (char-upcase   (integer->char #x03BB)))) ; l->L
(chk "6.6-downcase-greek" #x03BB (char->integer (char-downcase (integer->char #x039B)))) ; L->l
(chk "6.6-upcase-cyril"   #x0414 (char->integer (char-upcase   (integer->char #x0434)))) ; d->D
(chk "6.6-downcase-cyril" #x0434 (char->integer (char-downcase (integer->char #x0414)))) ; D->d
(chk "6.6-upper?-greek"   #t (char-upper-case? (integer->char #x039B)))
(chk "6.6-lower?-greek"   #t (char-lower-case? (integer->char #x03BB)))
(chk "6.6-upper?-cyril"   #t (char-upper-case? (integer->char #x0414)))
;;; character WRITE form -- all 9 R7RS 6.6 named chars, then a write->read roundtrip
(chk "6.6-w-null"   "#\\null"      (w->s (integer->char 0)))
(chk "6.6-w-alarm"  "#\\alarm"     (w->s (integer->char 7)))
(chk "6.6-w-bs"     "#\\backspace" (w->s (integer->char 8)))
(chk "6.6-w-tab"    "#\\tab"       (w->s (integer->char 9)))
(chk "6.6-w-nl"     "#\\newline"   (w->s (integer->char 10)))
(chk "6.6-w-ret"    "#\\return"    (w->s (integer->char 13)))
(chk "6.6-w-esc"    "#\\escape"    (w->s (integer->char 27)))
(chk "6.6-w-space"  "#\\space"     (w->s (integer->char 32)))
(chk "6.6-w-del"    "#\\delete"    (w->s (integer->char 127)))
(chk "6.6-w-A"      "#\\A"         (w->s #\A))
(chk "6.6-w-lambda" "#\\x03BB"     (w->s (integer->char 955)))
(chk "6.6-w-rt-esc" #t (let ((c (integer->char 27))) (eqv? c (read (open-input-string (w->s c))))))
(chk "6.6-w-rt-del" #t (let ((c (integer->char 127))) (eqv? c (read (open-input-string (w->s c))))))

(news ";;;6.7 Strings\n")
(chk "6.7-lit1" #t (string? "The word \"recursion\" has many meanings."))
(chk "6.7-lit-nl" 2 (length (string-split "Another example:\ntwo lines of text" #\newline)))
(chk "6.7-line-cont" "Here's text containing just one line"
  "Here's text \
containing just one line")
(chk "6.7-alpha" #\x03B1 (string-ref "\x03B1; is named GREEK SMALL LETTER ALPHA." 0))
(define ma "12345")
(define mb (string-copy "abcde"))
(string-copy! mb 1 ma 0 2)
(chk "6.7-scopy!" "a12de" mb)

;;; UTF-8 / character-vs-byte indexing.  Every one of these passed while the string procedures
;;; were byte-indexed IF you only ever fed them ASCII -- which is why the defect survived three
;;; filings (B27, B47, B146).  The multi-byte cases are the ones that discriminate, and the
;;; WIDTH-CHANGING mutations below are the ones no other suite reaches: replacing a 1-byte
;;; character with a 3-byte one changes the string's byte length, so it exercises the in-place
;;; grow/shrink path (and, for a long string, the reallocate-and-repoint path) rather than a
;;; plain overwrite.
(chk "6.7-u8-length"   4 (string-length "\x03B1;\x03B2;\x03B3;\x03B4;"))
(chk "6.7-u8-ref"      #\x03B3 (string-ref "\x03B1;\x03B2;\x03B3;\x03B4;" 2))
(chk "6.7-u8-substr"   "\x03B2;\x03B3;" (substring "\x03B1;\x03B2;\x03B3;\x03B4;" 1 3))
(chk "6.7-u8-s2l"      (list #\x03B1 #\x03B2) (string->list "\x03B1;\x03B2;"))
(chk "6.7-u8-s2l-rng"  (list #\x03B2 #\x03B3) (string->list "\x03B1;\x03B2;\x03B3;\x03B4;" 1 3))
(chk "6.7-u8-scopy-rng" "\x03B2;\x03B3;" (string-copy "\x03B1;\x03B2;\x03B3;\x03B4;" 1 3))
(chk "6.7-u8-l2s"      "\x03B1;\x03B2;" (list->string (list #\x03B1 #\x03B2)))
(chk "6.7-u8-string"   "\x03B1;\x03B2;" (string #\x03B1 #\x03B2))
(chk "6.7-u8-mkstring" "\x03BB;\x03BB;\x03BB;" (make-string 3 #\x03BB))
(chk "6.7-u8-append"   "\x03B1;\x03B2;" (string-append "\x03B1;" "\x03B2;"))
(chk "6.7-u8-s2v"      (vector #\x03B1 #\x03B2) (string->vector "\x03B1;\x03B2;"))
(chk "6.7-u8-v2s"      "\x03B1;\x03B2;" (vector->string (vector #\x03B1 #\x03B2)))
(chk "6.7-u8-s2utf8"   4 (bytevector-length (string->utf8 "\x03B1;\x03B2;\x03B3;\x03B4;" 0 2)))
(chk "6.7-u8-roundtrip" "\x03B1;\x03B2;" (utf8->string (string->utf8 "\x03B1;\x03B2;")))
;; set!: 1 byte -> 2 bytes on a HEAP string (grows, reallocates), then back down (shrinks in place)
(define u8h (string-copy "abcdefghijklmnop"))
(string-set! u8h 0 #\x03BB)
(chk "6.7-u8-set-grow"    "\x03BB;bcdefghijklmnop" u8h)
(chk "6.7-u8-set-grow-len" 16 (string-length u8h))
(string-set! u8h 0 #\Z)
(chk "6.7-u8-set-shrink"  "Zbcdefghijklmnop" u8h)
;; set! on a short IMMEDIATE string, where growth is bounded by the cell's own capacity
(define u8i (string-copy "ab"))
(string-set! u8i 0 #\x03BB)
(chk "6.7-u8-set-imm"     "\x03BB;b" u8i)
;; set! that pushes an IMMEDIATE string PAST the cell's inline capacity, forcing the in-situ
;; T_STR_IMM -> T_STR_HEAP promotion.  The capacity is sizeof(Cell)-3, which differs by target
;; (9 bytes on the 12-byte ESP32 cell, 21 on a 64-bit host), so both lengths are exercised: each
;; target promotes on one of them and merely grows inline on the other, and the ANSWER must be
;! identical either way.  A bad promotion shows up here as a truncated or garbage string.
(define u8p9 (string-copy "abcdefghi"))
(string-set! u8p9 0 #\x03BB)
(chk "6.7-u8-promote-9"    "\x03BB;bcdefghi" u8p9)
(chk "6.7-u8-promote-9-len" 9 (string-length u8p9))
(define u8p21 (string-copy "abcdefghijklmnopqrstu"))
(string-set! u8p21 20 #\x03BB)
(chk "6.7-u8-promote-21"   "abcdefghijklmnopqrst\x03BB;" u8p21)
(chk "6.7-u8-promote-21-len" 21 (string-length u8p21))
;; and the promoted cell must still behave as a normal mutable string afterwards
(string-set! u8p9 0 #\A)
(chk "6.7-u8-promote-reuse" "Abcdefghi" u8p9)
;; fill! with a wider character, then a narrower one
(define u8f (string-copy "abcdefghij"))
(string-fill! u8f #\x03BB 2 5)
(chk "6.7-u8-fill-grow"   "ab\x03BB;\x03BB;\x03BB;fghij" u8f)
(string-fill! u8f #\z 2 5)
(chk "6.7-u8-fill-shrink" "abzzzfghij" u8f)
;; copy! where source and destination characters differ in byte width
(define u8t (string-copy "abcdefghij"))
(string-copy! u8t 1 "\x03BB;\x03BC;" 0 2)
(chk "6.7-u8-copy-grow"   "a\x03BB;\x03BC;defghij" u8t)
(chk "6.7-u8-copy-len"    10 (string-length u8t))
;; copy! from a string INTO ITSELF: the widening path frees the old buffer, so the source span
;; has to be snapshotted first or it dangles.
(define u8s (string-copy "abcdefgh"))
(string-copy! u8s 0 u8s 2 5)
(chk "6.7-u8-copy-self"   "cdedefgh" u8s)

(news ";;;6.8 Vectors\n")
(chk "6.8-vec" '#(a b c) (vector 'a 'b 'c))
(chk "6.8-vref" 8 (vector-ref '#(1 1 2 3 5 8 13 21) 5))
(chk "6.8-vref2" 13 (vector-ref '#(1 1 2 3 5 8 13 21) (exact (round (* 2 (acos -1))))))
(chk "6.8-vset" '#(0 ("Sue" "Sue") "Anna")
  (let ((vec (vector 0 '(2 2 2 2) "Anna"))) (vector-set! vec 1 '("Sue" "Sue")) vec))
(chk "6.8-v2l" '(dah dah didah) (vector->list '#(dah dah didah)))
(chk "6.8-v2l-range" '(dah) (vector->list '#(dah dah didah) 1 2))
(chk "6.8-l2v" '#(dididit dah) (list->vector '(dididit dah)))
(chk "6.8-s2v" '#(#\A #\B #\C) (string->vector "ABC"))
(chk "6.8-v2s" "123" (vector->string '#(#\1 #\2 #\3)))
(define va (vector 1 2 3 4 5))
(define vb (vector 10 20 30 40 50))
(vector-copy! vb 1 va 0 2)
(chk "6.8-vcopy!" '#(10 1 2 40 50) vb)
(chk "6.8-vappend" '#(a b c d e f) (vector-append '#(a b c) '#(d e f)))
(define vc (vector 1 2 3 4 5))
(vector-fill! vc 'smash 2 4)
(chk "6.8-vfill!" '#(1 2 smash smash 5) vc)
;;; vector WRITE form -- was "#vector(...)"; must be R7RS "#(...)"
(chk "6.8-w-vec"   "#(1 2 3)"      (w->s (vector 1 2 3)))
(chk "6.8-w-nest"  "#(a #(b c) d)" (w->s (vector 'a (vector 'b 'c) 'd)))
(chk "6.8-w-empty" "#()"           (w->s (vector)))

(news ";;;6.9 Bytevectors\n")
(chk "6.9-lit" (bytevector 0 10 5) (bytevector 0 10 5))
(chk "6.9-make" (bytevector 12 12) (make-bytevector 2 12))
(chk "6.9-ref" 8 (bytevector-u8-ref (bytevector 1 1 2 3 5 8 13 21) 5))
(chk "6.9-set" (bytevector 1 3 3 4) (let ((bv (bytevector 1 2 3 4))) (bytevector-u8-set! bv 1 3) bv))
(chk "6.9-copy" (bytevector 3 4) (bytevector-copy (bytevector 1 2 3 4 5) 2 4))
(define bva (bytevector 1 2 3 4 5))
(define bvb (bytevector 10 20 30 40 50))
(bytevector-copy! bvb 1 bva 0 2)
(chk "6.9-copy!" (bytevector 10 1 2 40 50) bvb)
(chk "6.9-append" (bytevector 0 1 2 3 4 5) (bytevector-append (bytevector 0 1 2) (bytevector 3 4 5)))
(chk "6.9-utf8->s" "A" (utf8->string (bytevector #x41)))
(chk "6.9-s->utf8" (bytevector 206 187) (string->utf8 "\x03BB;"))
;;; bytevector WRITE form -- was "#bytevector(...)"; must be R7RS "#u8(...)"
(chk "6.9-w-bv"    "#u8(0 10 255)" (w->s (bytevector 0 10 255)))
(chk "6.9-w-empty" "#u8()"         (w->s (make-bytevector 0)))

(news ";;;6.10 Control features\n")
(chk "6.10-proc-car" #t (procedure? car))
(chk "6.10-proc-qcar" #f (procedure? 'car))
(chk "6.10-proc-lam" #t (procedure? (lambda (x) (* x x))))
(chk "6.10-proc-qlam" #f (procedure? '(lambda (x) (* x x))))
(chk "6.10-apply" 7 (apply + (list 3 4)))
(define compose (lambda (f g) (lambda args (f (apply g args)))))
(chk "6.10-compose" 30 ((compose sqrt *) 12 75))
(chk "6.10-map-cadr" '(b e h) (map cadr '((a b) (d e) (g h))))
(chk "6.10-map-expt" '(1 4 27 256 3125) (map (lambda (n) (expt n n)) '(1 2 3 4 5)))
;;; R7RS 6.10: map/for-each terminate at the SHORTEST list (was: error on unequal lengths)
(chk "6.10-map-uneq"  '(11 22) (map + '(1 2 3) '(10 20)))
(chk "6.10-map-uneq2" '(11 22) (map + '(1 2) '(10 20 30)))
(chk "6.10-map-3lst"  '(111 222) (map + '(1 2) '(10 20 30) '(100 200 300 400)))
(chk "6.10-fe-uneq"   3 (let ((n 0)) (for-each (lambda (a b) (set! n (+ n a))) '(1 2 3) '(10 20)) n))
(chk "6.10-map-count" '(1 2)
  (let ((count 0)) (map (lambda (ignored) (set! count (+ count 1)) count) '(a b))))
(chk "6.10-smap-fold" "abdegh" (string-map char-foldcase "AbdEgH"))
(chk "6.10-smap-incr" "IBM"
  (string-map (lambda (c) (integer->char (+ 1 (char->integer c)))) "HAL"))
(chk "6.10-smap-2" "StUdLyCaPs"
  (string-map (lambda (c k) ((if (eqv? k #\u) char-upcase char-downcase) c)) "studlycaps xxx" "ululululul"))
(chk "6.10-vmap-cadr" '#(b e h) (vector-map cadr '#((a b) (d e) (g h))))
(chk "6.10-vmap-expt" '#(1 4 27 256 3125) (vector-map (lambda (n) (expt n n)) '#(1 2 3 4 5)))
(chk "6.10-vmap-add" '#(5 7 9) (vector-map + '#(1 2 3) '#(4 5 6 7)))
(chk "6.10-vmap-count" '#(1 2)
  (let ((count 0)) (vector-map (lambda (ignored) (set! count (+ count 1)) count) '#(a b))))
(chk "6.10-for-each" '#(0 1 4 9 16)
  (let ((v (make-vector 5))) (for-each (lambda (i) (vector-set! v i (* i i))) '(0 1 2 3 4)) v))
(chk "6.10-sfor-each" '(101 100 99 98 97)
  (let ((v '())) (string-for-each (lambda (c) (set! v (cons (char->integer c) v))) "abcde") v))
(chk "6.10-vfor-each" '(0 1 4 9 16)
  (let ((v (make-list 5))) (vector-for-each (lambda (i) (list-set! v i (* i i))) '#(0 1 2 3 4)) v))

(display "rxrs-tests: ") (display rxrs-pass) (display " pass, ")
(display rxrs-fail) (display " fail\n")

; end of rxrs-tests.scm
