var searchData=
[
  ['machine_0',['Machine',['../index.html#autotoc_md43',1,'AI and Machine-to-Machine'],['../index.html#arch-bc',1,'Bytecode Virtual Machine'],['../index.html#autotoc_md31',1,'LambLisp Virtual Machine']]],
  ['machine_20to_20machine_1',['AI and Machine-to-Machine',['../index.html#autotoc_md43',1,'']]],
  ['machines_2',['Control Applications as Virtual Machines.',['../index.html#autotoc_md32',1,'']]],
  ['macro_3',['macro',['../index.html#arch-lambda',1,'lambda, nlambda, and macro'],['../index.html#autotoc_md51',1,'macro']]],
  ['management_4',['Memory Management',['../index.html#autotoc_md34',1,'']]],
  ['map_5',['4.5 Collecting the Map',['../index.html#fwd-jetson-collect',1,'']]],
  ['map_20accumulator_20floor_20map_20scm_6',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['map_20scm_7',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['map_20store_20and_20ascii_20render_8',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['mapping_20demo_20telemetry_20scm_9',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md115',1,'']]],
  ['mapping_20with_20the_20freenove_204wd_20car_10',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['marshaling_11',['Data Marshaling',['../index.html#autotoc_md63',1,'']]],
  ['master_12',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['master_13',['PROFIBUS DP master',['../index.html#autotoc_md109',1,'']]],
  ['math_20linear_20algebra_14',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['matrix_15',['LambLisp Compatibility Matrix',['../index.html#compat-matrix',1,'']]],
  ['memory_20and_20gc_20tuning_16',['Memory and GC Tuning',['../index.html#arch-adaptive',1,'']]],
  ['memory_20and_20pre_20reserve_17',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['memory_20footprint_18',['What is the memory footprint?',['../index.html#autotoc_md193',1,'']]],
  ['memory_20management_19',['Memory Management',['../index.html#autotoc_md34',1,'']]],
  ['memory_20model_20and_20list_20structures_20',['Cell Memory Model and List Structures',['../index.html#autotoc_md36',1,'']]],
  ['memory_20tuning_21',['GC and memory tuning',['../index.html#autotoc_md75',1,'']]],
  ['memory_20tuning_3a_20stack_20size_20dma_20memory_20and_20pre_20reserve_22',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['micro_20controllers_23',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['microprocessors_24',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['microsecond_20isr_25',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md39',1,'']]],
  ['modbus_20controller_26',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['modbus_20interface_27',['LambLisp Modbus Interface',['../index.html#modbus',1,'']]],
  ['modbus_20peripheral_28',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['modbus_20request_29',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md107',1,'']]],
  ['model_30',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['model_31',['model',['../index.html#profinet-device-model',1,'5.3 Device model'],['../index.html#autotoc_md71',1,'The boot-confirm / rollback model']]],
  ['model_20and_20list_20structures_32',['Cell Memory Model and List Structures',['../index.html#autotoc_md36',1,'']]],
  ['module_33',['3.5 Bee Strategy Module',['../index.html#fwd-bee-onboard',1,'']]],
  ['motion_20primitives_34',['3.2 Motion Primitives',['../index.html#fwd-motion',1,'']]],
  ['motors_20pca9685_20scm_35',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md94',1,'']]],
  ['multi_20platform_36',['Multi-platform',['../index.html#autotoc_md14',1,'']]],
  ['multi_20platform_20support_37',['Multi-Platform Support',['../index.html#arch-multiplatform',1,'']]],
  ['music_20scm_38',['Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)',['../index.html#autotoc_md116',1,'']]],
  ['musical_20notes_20music_20scm_39',['Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)',['../index.html#autotoc_md116',1,'']]]
];
