var searchData=
[
  ['o_20esp32_20and_20compatible_0',['Arduino / Embedded I/O (ESP32 and compatible)',['../index.html#autotoc_md67',1,'']]],
  ['object_20system_1',['Lightweight object system',['../index.html#autotoc_md57',1,'']]],
  ['objects_2',['Stateful Objects',['../index.html#autotoc_md59',1,'']]],
  ['objects_20and_20non_20symbol_20keys_3',['Objects and non-symbol keys',['../index.html#autotoc_md56',1,'']]],
  ['objects_20are_20wrappers_20around_20hierarchical_20dictionaries_4',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md29',1,'']]],
  ['oblist_5',['The oblist',['../index.html#autotoc_md55',1,'']]],
  ['of_20existing_20c_20arduino_20libraries_6',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md16',1,'']]],
  ['of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_7',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['of_20lisp_20and_20scheme_8',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['of_20scheme_9',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md176',1,'']]],
  ['of_20the_20freenove_204wd_20car_10',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md85',1,'']]],
  ['on_11',['What hardware does LambLisp run on?',['../index.html#autotoc_md158',1,'']]],
  ['on_20all_20platforms_12',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md173',1,'']]],
  ['on_20board_20car_20code_13',['3. On-Board Car Code',['../index.html#fwd-onboard',1,'']]],
  ['on_20board_20display_20esp32_20s3_20eye_14',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['on_20embedded_20hardware_15',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md30',1,'']]],
  ['on_20linux_16',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['on_20micro_20controllers_17',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['on_20the_20jetson_18',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['onewire_201_20wire_20bus_19',['OneWire (1-Wire Bus)',['../index.html#onewire',1,'']]],
  ['open_20api_20for_20new_20lisp_20primitives_20',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md18',1,'']]],
  ['open_20source_21',['Is LambLisp open source?',['../index.html#autotoc_md160',1,'']]],
  ['opening_20a_20peripheral_22',['3.1 Opening a Peripheral',['../index.html#modbus-peripheral-open',1,'']]],
  ['opening_20the_20bus_23',['2.1 Opening the Bus',['../index.html#profibus-open',1,'']]],
  ['operation_24',['Operation',['../index.html#autotoc_md186',1,'Integration and Operation'],['../index.html#autotoc_md80',1,'The eval Operation']]],
  ['operations_25',['Operations',['../index.html#autotoc_md65',1,'Dictionary (Environment) Operations'],['../index.html#autotoc_md79',1,'Operations']]],
  ['orchestration_20and_20the_20robot_20stack_26',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['organization_27',['Interpreter &amp;amp; compiler organization',['../index.html#arch-interp',1,'']]],
  ['other_20scheme_20implementations_28',['Other Scheme Implementations',['../index.html#competitors',1,'']]],
  ['output_29',['Input and Output',['../index.html#autotoc_md149',1,'']]],
  ['over_20the_20air_20updates_30',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['over_20the_20air_20updates_20without_20reboot_31',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md19',1,'']]],
  ['overview_32',['Overview',['../index.html#modbus-overview',1,'1. Overview'],['../index.html#fwd-overview',1,'1. Overview'],['../index.html#autotoc_md35',1,'Overview']]]
];
