var searchData=
[
  ['c_0',['Camera / LCD primitives (C++)',['../index.html#autotoc_md92',1,'']]],
  ['c_20—_20footprint_1',['Group C — Footprint',['../index.html#autotoc_md46',1,'']]],
  ['c_20api_2',['Language Internals and C++ API',['../index.html#autotoc_md48',1,'']]],
  ['c_20arduino_20libraries_3',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md16',1,'']]],
  ['c_20c_20code_4',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md189',1,'']]],
  ['c_20c_20on_20micro_20controllers_5',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['c_20code_6',['C code',['../index.html#autotoc_md189',1,'Does LambLisp interoperate with C/C++ code?'],['../index.html#autotoc_md25',1,'Runtime collaboration with C++ code']]],
  ['c_20extension_7',['C++ Extension',['../index.html#autotoc_md45',1,'']]],
  ['c_20integration_8',['C++ Integration',['../index.html#arch-cpp',1,'']]],
  ['c_20on_20micro_20controllers_9',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['call_20with_20current_20continuation_10',['Why no &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md178',1,'']]],
  ['callbacks_11',['3.5 Write Callbacks',['../index.html#modbus-write-callbacks',1,'']]],
  ['called_20lamblisp_20instead_20of_20scheme_12',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md176',1,'']]],
  ['calls_13',['Tail recursion and tail-calls',['../index.html#autotoc_md23',1,'']]],
  ['cam_20scm_20live_20preview_20layer_14',['eye-cam.scm live-preview layer',['../index.html#autotoc_md93',1,'']]],
  ['camera_20and_20on_20board_20display_20esp32_20s3_20eye_15',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['camera_20lcd_20primitives_20c_16',['Camera / LCD primitives (C++)',['../index.html#autotoc_md92',1,'']]],
  ['can_20i_20use_20lamblisp_20without_20an_20rtos_17',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md191',1,'']]],
  ['car_18',['Car',['../index.html#fwd-jetson-waypoints',1,'4.3 Feeding Waypoints to the Car'],['../index.html#fwd-run-car',1,'6.2 Flash and Start the Car'],['../index.html#fwd-floor-mapping',1,'Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car'],['../index.html#autotoc_md85',1,'Worked Example: Supervisory Control of the Freenove 4WD Car']]],
  ['car_20code_19',['3. On-Board Car Code',['../index.html#fwd-onboard',1,'']]],
  ['car_20kit_20—_20peripheral_20summary_20',['Freenove 4WD Car Kit — Peripheral Summary',['../index.html#autotoc_md91',1,'']]],
  ['ceiling_20and_20why_20it_20exists_21',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['cell_20memory_20model_20and_20list_20structures_22',['Cell Memory Model and List Structures',['../index.html#autotoc_md36',1,'']]],
  ['certification_20and_20naming_23',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['characters_24',['Characters',['../index.html#autotoc_md135',1,'']]],
  ['class_20data_20types_25',['Procedures are first-class data types',['../index.html#autotoc_md24',1,'']]],
  ['class_20hierarchical_20dictionaries_26',['First-class hierarchical dictionaries',['../index.html#autotoc_md20',1,'']]],
  ['client_20api_20llip_20client_20scm_27',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md81',1,'']]],
  ['client_20scm_28',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md81',1,'']]],
  ['client_3a_20tools_20llip_29',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['cloud_20server_30',['6.1 Start the Cloud Server',['../index.html#fwd-run-cloud',1,'']]],
  ['cloud_20strategy_20server_31',['5. Cloud Strategy Server',['../index.html#fwd-cloud',1,'']]],
  ['code_32',['Code',['../index.html#fwd-onboard',1,'3. On-Board Car Code'],['../index.html#arch-pipeline',1,'Execution Tiers: AST → Bytecode → Native Code']]],
  ['code_33',['code',['../index.html#autotoc_md189',1,'Does LambLisp interoperate with C/C++ code?'],['../index.html#autotoc_md25',1,'Runtime collaboration with C++ code']]],
  ['code_20generation_34',['Why not use LLVM for native code generation?',['../index.html#autotoc_md184',1,'']]],
  ['code_20generator_20ncg_35',['Native Code Generator (NCG)',['../index.html#arch-ncg',1,'']]],
  ['code_20lifecycle_3a_20incremental_20hot_20reload_36',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['code_20run_20on_20all_20platforms_37',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md173',1,'']]],
  ['code_20without_20reflashing_38',['How do I update code without reflashing?',['../index.html#autotoc_md162',1,'']]],
  ['codes_39',['2.3 Function Codes',['../index.html#modbus-function-codes',1,'']]],
  ['codes_20symbols_20for_20modbus_20request_40',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md107',1,'']]],
  ['collaboration_20with_20c_20code_41',['Runtime collaboration with C++ code',['../index.html#autotoc_md25',1,'']]],
  ['collecting_20the_20map_42',['4.5 Collecting the Map',['../index.html#fwd-jetson-collect',1,'']]],
  ['collection_43',['Garbage Collection',['../index.html#arch-gc',1,'']]],
  ['collection_44',['Adaptive real-time garbage collection',['../index.html#autotoc_md17',1,'']]],
  ['collisions_45',['Hash table sizing and collisions',['../index.html#autotoc_md54',1,'']]],
  ['combination_20with_20c_20c_20on_20micro_20controllers_46',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['command_20line_20client_3a_20tools_20llip_47',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['compatibility_48',['Detailed Compatibility',['../index.html#autotoc_md122',1,'']]],
  ['compatibility_20matrix_49',['LambLisp Compatibility Matrix',['../index.html#compat-matrix',1,'']]],
  ['compatible_50',['Arduino / Embedded I/O (ESP32 and compatible)',['../index.html#autotoc_md67',1,'']]],
  ['compilation_51',['compilation',['../index.html#autotoc_md21',1,'Incremental, just-in-time compilation'],['../index.html#autotoc_md171',1,'What is bytecode / NCG compilation?']]],
  ['compiled_20tier_20does_20not_20run_20on_20embedded_20hardware_52',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md30',1,'']]],
  ['compiler_20organization_53',['Interpreter &amp;amp; compiler organization',['../index.html#arch-interp',1,'']]],
  ['concepts_54',['Concepts',['../index.html#autotoc_md164',1,'']]],
  ['confirm_20rollback_20model_55',['The boot-confirm / rollback model',['../index.html#autotoc_md71',1,'']]],
  ['conformance_56',['Language and Conformance',['../index.html#autotoc_md175',1,'']]],
  ['connect_20to_20the_20repl_57',['Connect to the REPL',['../index.html#autotoc_md8',1,'']]],
  ['connecting_58',['2.1 Connecting',['../index.html#modbus-controller-connect',1,'']]],
  ['connection_20lifecycle_59',['Connection Lifecycle',['../index.html#autotoc_md78',1,'']]],
  ['connections_60',['4.1 Connections',['../index.html#fwd-jetson-connect',1,'']]],
  ['constructors_61',['Task Constructors',['../index.html#autotoc_md103',1,'']]],
  ['containers_62',['Containers',['../index.html#autotoc_md58',1,'']]],
  ['continuation_63',['Why no &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md178',1,'']]],
  ['contract_20nvs_64',['The loader wire contract (NVS)',['../index.html#autotoc_md70',1,'']]],
  ['control_65',['2.5 Diagnostics and Global Control',['../index.html#profibus-diag',1,'']]],
  ['control_66',['Real-time control',['../index.html#autotoc_md13',1,'']]],
  ['control_20applications_20as_20virtual_20machines_67',['Control Applications as Virtual Machines.',['../index.html#autotoc_md32',1,'']]],
  ['control_20cycle_68',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md38',1,'']]],
  ['control_20demo_20supervisor_20scm_69',['Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)',['../index.html#autotoc_md113',1,'']]],
  ['control_20features_70',['Control Features',['../index.html#autotoc_md143',1,'']]],
  ['control_20of_20the_20freenove_204wd_20car_71',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md85',1,'']]],
  ['control_20system_72',['What is a real-time control system?',['../index.html#autotoc_md165',1,'']]],
  ['controller_73',['Controller',['../index.html#modbus-controller',1,'2. LambLisp as Modbus Controller'],['../index.html#autotoc_md89',1,'PCA9685 PWM Controller']]],
  ['controller_20function_20codes_20symbols_20for_20modbus_20request_74',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md107',1,'']]],
  ['controller_20functions_75',['Controller Functions',['../index.html#autotoc_md106',1,'']]],
  ['controllers_76',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['convenience_20wrappers_20sonar_20scm_77',['Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)',['../index.html#autotoc_md102',1,'']]],
  ['cooperative_20scheduling_78',['Behaviors: Cooperative Scheduling',['../index.html#behaviors',1,'']]],
  ['core_20language_79',['Core Language',['../index.html#autotoc_md123',1,'']]],
  ['coverage_20plan_80',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['coverage_20planner_81',['5.1 Boustrophedon Coverage Planner',['../index.html#fwd-cloud-planner',1,'']]],
  ['coverage_20summary_82',['Coverage Summary',['../index.html#autotoc_md120',1,'']]],
  ['cryptography_83',['Cryptography',['../index.html#crypto',1,'']]],
  ['csv_84',['CSV',['../index.html#csv',1,'']]],
  ['cuda_20integration_85',['CUDA Integration',['../index.html#cuda-integration',1,'']]],
  ['current_20continuation_86',['Why no &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md178',1,'']]],
  ['cycle_87',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md38',1,'']]]
];
