var searchData=
[
  ['table_20and_20hashing_20details_0',['Hash table and hashing details',['../index.html#autotoc_md53',1,'']]],
  ['table_20sizing_20and_20collisions_1',['Hash table sizing and collisions',['../index.html#autotoc_md54',1,'']]],
  ['tables_2',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['tags_3',['Error tags',['../index.html#autotoc_md112',1,'']]],
  ['tail_20calls_4',['Tail recursion and tail-calls',['../index.html#autotoc_md23',1,'']]],
  ['tail_20recursion_20and_20tail_20calls_5',['Tail recursion and tail-calls',['../index.html#autotoc_md23',1,'']]],
  ['task_20constructors_6',['Task Constructors',['../index.html#autotoc_md103',1,'']]],
  ['task_20queue_7',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md40',1,'']]],
  ['tcp_20tls_20vs_20serial_8',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['telemetry_20floor_20mapping_20demo_20telemetry_20scm_9',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md115',1,'']]],
  ['telemetry_20scm_10',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md115',1,'']]],
  ['the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_11',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['the_20air_20updates_12',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['the_20air_20updates_20without_20reboot_13',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md19',1,'']]],
  ['the_20api_14',['5.2 The API',['../index.html#profinet-api',1,'']]],
  ['the_20baud_20ceiling_20and_20why_20it_20exists_15',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['the_20boot_20confirm_20rollback_20model_16',['The boot-confirm / rollback model',['../index.html#autotoc_md71',1,'']]],
  ['the_20bus_17',['2.1 Opening the Bus',['../index.html#profibus-open',1,'']]],
  ['the_20car_18',['the Car',['../index.html#fwd-jetson-waypoints',1,'4.3 Feeding Waypoints to the Car'],['../index.html#fwd-run-car',1,'6.2 Flash and Start the Car']]],
  ['the_20cloud_20server_19',['6.1 Start the Cloud Server',['../index.html#fwd-run-cloud',1,'']]],
  ['the_20compiled_20tier_20does_20not_20run_20on_20embedded_20hardware_20',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md30',1,'']]],
  ['the_20daemon_21',['5.1 Building the daemon',['../index.html#profinet-two-processes',1,'']]],
  ['the_20dictionary_20type_22',['The &lt;em&gt;dictionary&lt;/em&gt; type',['../index.html#arch-dict',1,'']]],
  ['the_20eval_20operation_23',['The eval Operation',['../index.html#autotoc_md80',1,'']]],
  ['the_20example_24',['the Example',['../index.html#fwd-run',1,'6. Running the Example'],['../index.html#fwd-extend',1,'7.3 Extending the Example']]],
  ['the_20four_20register_20tables_25',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['the_20freenove_204wd_20car_26',['the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car'],['../index.html#autotoc_md85',1,'Worked Example: Supervisory Control of the Freenove 4WD Car']]],
  ['the_20jetson_27',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['the_20lisp_20landscape_28',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md180',1,'']]],
  ['the_20loader_20wire_20contract_20nvs_29',['The loader wire contract (NVS)',['../index.html#autotoc_md70',1,'']]],
  ['the_20map_30',['4.5 Collecting the Map',['../index.html#fwd-jetson-collect',1,'']]],
  ['the_20memory_20footprint_31',['What is the memory footprint?',['../index.html#autotoc_md193',1,'']]],
  ['the_20non_20blocking_20request_20poll_20model_32',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['the_20numeric_20tower_33',['The Numeric Tower',['../index.html#autotoc_md127',1,'']]],
  ['the_20oblist_34',['The oblist',['../index.html#autotoc_md55',1,'']]],
  ['the_20queue_35',['The Queue',['../index.html#autotoc_md104',1,'']]],
  ['the_20repl_36',['the REPL',['../index.html#autotoc_md8',1,'Connect to the REPL'],['../index.html#autotoc_md3',1,'Using the REPL']]],
  ['the_20repository_37',['What&apos;s in the repository?',['../index.html#autotoc_md10',1,'']]],
  ['the_20robot_20stack_38',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['the_20same_20scheme_20code_20run_20on_20all_20platforms_39',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md173',1,'']]],
  ['the_20serve_20loop_40',['3.4 The Serve Loop',['../index.html#modbus-serve-loop',1,'']]],
  ['the_20service_20loop_41',['2.3 The Service Loop',['../index.html#profibus-loop',1,'']]],
  ['the_20supervisor_20on_20the_20jetson_42',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['the_20supervisory_20architecture_43',['Role in the Supervisory Architecture',['../index.html#autotoc_md84',1,'']]],
  ['the_20universal_20glue_44',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['the_20world_20pauses_45',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md37',1,'']]],
  ['three_20tiers_46',['7.1 Why Three Tiers?',['../index.html#fwd-why-three-tiers',1,'']]],
  ['tier_20does_20not_20run_20on_20embedded_20hardware_47',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md30',1,'']]],
  ['tiers_48',['7.1 Why Three Tiers?',['../index.html#fwd-why-three-tiers',1,'']]],
  ['tiers_3a_20ast_20→_20bytecode_20→_20native_20code_49',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['time_20—_20bounded_20control_20cycle_50',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md38',1,'']]],
  ['time_20compilation_51',['Incremental, just-in-time compilation',['../index.html#autotoc_md21',1,'']]],
  ['time_20control_52',['Real-time control',['../index.html#autotoc_md13',1,'']]],
  ['time_20control_20system_53',['What is a real-time control system?',['../index.html#autotoc_md165',1,'']]],
  ['time_20garbage_20collection_54',['Adaptive real-time garbage collection',['../index.html#autotoc_md17',1,'']]],
  ['time_20guarantees_55',['Real-time Guarantees',['../index.html#arch-realtime',1,'']]],
  ['time_20lamblisp_56',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['time_20lisp_20for_20microprocessors_57',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['timers_20scm_58',['Timers (&lt;span class=&quot;tt&quot;&gt;Timers.scm&lt;/span&gt;)',['../index.html#autotoc_md98',1,'']]],
  ['timers_20timers_20scm_59',['Timers (&lt;span class=&quot;tt&quot;&gt;Timers.scm&lt;/span&gt;)',['../index.html#autotoc_md98',1,'']]],
  ['timing_20and_20system_60',['Timing and system',['../index.html#autotoc_md74',1,'']]],
  ['tls_20vs_20serial_61',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['to_20esp32_62',['Deploy to ESP32',['../index.html#deploy-esp32',1,'']]],
  ['to_20machine_63',['AI and Machine-to-Machine',['../index.html#autotoc_md43',1,'']]],
  ['to_20the_20car_64',['4.3 Feeding Waypoints to the Car',['../index.html#fwd-jetson-waypoints',1,'']]],
  ['to_20the_20repl_65',['Connect to the REPL',['../index.html#autotoc_md8',1,'']]],
  ['tools_66',['Diagnostics and Development Tools',['../index.html#autotoc_md66',1,'']]],
  ['tools_20llip_67',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['tower_68',['The Numeric Tower',['../index.html#autotoc_md127',1,'']]],
  ['transport_20and_20arq_20llip_20serial_20scm_69',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['transport_20scm_70',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['transports_3a_20tcp_20tls_20vs_20serial_71',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['try_20lamblisp_20on_20linux_72',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['try_20lamblisp_20right_20now_73',['How do I try LambLisp right now?',['../index.html#autotoc_md156',1,'']]],
  ['tuning_74',['Tuning',['../index.html#arch-adaptive',1,'Memory and GC Tuning'],['../index.html#gc-tuning',1,'Runtime and GC Tuning']]],
  ['tuning_75',['GC and memory tuning',['../index.html#autotoc_md75',1,'']]],
  ['tuning_20parameters_76',['6.4 Tuning Parameters',['../index.html#fwd-run-tuning',1,'']]],
  ['tuning_3a_20stack_20size_20dma_20memory_20and_20pre_20reserve_77',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['twin_78',['Digital Twin',['../index.html#autotoc_md86',1,'']]],
  ['twin_20sync_79',['4.4 Digital Twin Sync',['../index.html#fwd-jetson-twin',1,'']]],
  ['type_80',['The &lt;em&gt;dictionary&lt;/em&gt; type',['../index.html#arch-dict',1,'']]],
  ['type_20system_81',['Type System',['../index.html#autotoc_md125',1,'']]],
  ['typed_20numeric_20arrays_20array_82',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['types_83',['Procedures are first-class data types',['../index.html#autotoc_md24',1,'']]]
];
