var searchData=
[
  ['daemon_0',['5.1 Building the daemon',['../index.html#profinet-two-processes',1,'']]],
  ['data_1',['Structured Data',['../index.html#structured-data',1,'']]],
  ['data_20marshaling_2',['Data Marshaling',['../index.html#autotoc_md63',1,'']]],
  ['data_20types_3',['Procedures are first-class data types',['../index.html#autotoc_md24',1,'']]],
  ['declaring_20slaves_4',['2.2 Declaring Slaves',['../index.html#profibus-add-slave',1,'']]],
  ['deferred_20task_20queue_5',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md40',1,'']]],
  ['demo_20sandbox_20scm_6',['Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)',['../index.html#autotoc_md114',1,'']]],
  ['demo_20supervisor_20scm_7',['Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)',['../index.html#autotoc_md113',1,'']]],
  ['demo_20telemetry_20scm_8',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md115',1,'']]],
  ['demos_9',['Bundled Demos',['../index.html#demos',1,'']]],
  ['deploy_20to_20esp32_10',['Deploy to ESP32',['../index.html#deploy-esp32',1,'']]],
  ['derivatives_11',['Why not use embedded Python derivatives?',['../index.html#autotoc_md182',1,'']]],
  ['detailed_20compatibility_12',['Detailed Compatibility',['../index.html#autotoc_md122',1,'']]],
  ['details_13',['Hash table and hashing details',['../index.html#autotoc_md53',1,'']]],
  ['development_20tools_14',['Diagnostics and Development Tools',['../index.html#autotoc_md66',1,'']]],
  ['device_15',['PROFINET IO-Device',['../index.html#autotoc_md111',1,'']]],
  ['device_20initiated_20serving_20llip_20transport_20scm_16',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['device_20model_17',['5.3 Device model',['../index.html#profinet-device-model',1,'']]],
  ['device_20patterns_18',['Device Patterns',['../index.html#autotoc_md60',1,'']]],
  ['diagnostics_20and_20development_20tools_19',['Diagnostics and Development Tools',['../index.html#autotoc_md66',1,'']]],
  ['diagnostics_20and_20global_20control_20',['2.5 Diagnostics and Global Control',['../index.html#profibus-diag',1,'']]],
  ['diagram_21',['LambLisp Block Diagram',['../index.html#autotoc_md33',1,'']]],
  ['dictionaries_22',['dictionaries',['../index.html#autotoc_md20',1,'First-class hierarchical dictionaries'],['../index.html#arch-hierdict',1,'Hierarchical dictionaries'],['../index.html#autotoc_md29',1,'Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;']]],
  ['dictionary_23',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['dictionary_20environment_20operations_24',['Dictionary (Environment) Operations',['../index.html#autotoc_md65',1,'']]],
  ['dictionary_20type_25',['The &lt;em&gt;dictionary&lt;/em&gt; type',['../index.html#arch-dict',1,'']]],
  ['digital_20twin_26',['Digital Twin',['../index.html#autotoc_md86',1,'']]],
  ['digital_20twin_20sync_27',['4.4 Digital Twin Sync',['../index.html#fwd-jetson-twin',1,'']]],
  ['display_28',['LCD1602 Display',['../index.html#autotoc_md88',1,'']]],
  ['display_20esp32_20s3_20eye_29',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['distributed_20environment_30',['Unified Distributed Environment',['../index.html#autotoc_md87',1,'']]],
  ['distribution_31',['Proprietary Distribution',['../index.html#autotoc_md62',1,'']]],
  ['dma_20memory_20and_20pre_20reserve_32',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['do_20i_20try_20lamblisp_20right_20now_33',['How do I try LambLisp right now?',['../index.html#autotoc_md156',1,'']]],
  ['do_20i_20update_20code_20without_20reflashing_34',['How do I update code without reflashing?',['../index.html#autotoc_md162',1,'']]],
  ['does_20lamblisp_20interoperate_20with_20c_20c_20code_35',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md189',1,'']]],
  ['does_20lamblisp_20run_20on_36',['What hardware does LambLisp run on?',['../index.html#autotoc_md158',1,'']]],
  ['does_20lamblisp_20sit_20in_20the_20lisp_20landscape_37',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md180',1,'']]],
  ['does_20not_20run_20on_20embedded_20hardware_38',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md30',1,'']]],
  ['does_20the_20same_20scheme_20code_20run_20on_20all_20platforms_39',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md173',1,'']]],
  ['dp_20as_20a_20master_40',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['dp_20as_20a_20slave_41',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['dp_20master_42',['PROFIBUS DP master',['../index.html#autotoc_md109',1,'']]],
  ['dp_20slave_43',['PROFIBUS DP slave',['../index.html#autotoc_md110',1,'']]]
];
