var searchData=
[
  ['fast_20is_20lamblisp_0',['How fast is LambLisp?',['../index.html#autotoc_md169',1,'']]],
  ['feature_20footprint_1',['Feature Footprint',['../index.html#autotoc_md47',1,'']]],
  ['feature_20summary_2',['Key feature summary',['../index.html#autotoc_md26',1,'']]],
  ['features_3',['Control Features',['../index.html#autotoc_md143',1,'']]],
  ['feeding_20waypoints_20to_20the_20car_4',['4.3 Feeding Waypoints to the Car',['../index.html#fwd-jetson-waypoints',1,'']]],
  ['fill_20behaviour_5',['3.3 Autonomous Fill Behaviour',['../index.html#fwd-autonomous',1,'']]],
  ['first_20class_20data_20types_6',['Procedures are first-class data types',['../index.html#autotoc_md24',1,'']]],
  ['first_20class_20hierarchical_20dictionaries_7',['First-class hierarchical dictionaries',['../index.html#autotoc_md20',1,'']]],
  ['flag_20summary_8',['4.3 Build Flag Summary',['../index.html#modbus-build-flags',1,'']]],
  ['flags_9',['7. Build Flags',['../index.html#fieldbus-build-flags',1,'']]],
  ['flash_10',['Build and Flash',['../index.html#autotoc_md7',1,'']]],
  ['flash_20and_20start_20the_20car_11',['6.2 Flash and Start the Car',['../index.html#fwd-run-car',1,'']]],
  ['float32_20helpers_12',['2.4 Float32 Helpers',['../index.html#modbus-float32',1,'']]],
  ['floor_20map_20scm_13',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['floor_20mapping_20demo_20telemetry_20scm_14',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md115',1,'']]],
  ['floor_20mapping_20with_20the_20freenove_204wd_20car_15',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['footprint_16',['Footprint',['../index.html#autotoc_md47',1,'Feature Footprint'],['../index.html#autotoc_md46',1,'Group C — Footprint']]],
  ['footprint_17',['What is the memory footprint?',['../index.html#autotoc_md193',1,'']]],
  ['for_20microprocessors_18',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['for_20modbus_20request_19',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md107',1,'']]],
  ['for_20native_20code_20generation_20',['Why not use LLVM for native code generation?',['../index.html#autotoc_md184',1,'']]],
  ['for_20new_20lisp_20primitives_21',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md18',1,'']]],
  ['format_22',['Wire Format',['../index.html#autotoc_md77',1,'']]],
  ['forms_23',['Syntax Forms',['../index.html#autotoc_md61',1,'']]],
  ['four_20register_20tables_24',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['framing_20struct_25',['Binary framing (struct)',['../index.html#struct',1,'']]],
  ['freenove_204wd_20car_26',['Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car'],['../index.html#autotoc_md85',1,'Worked Example: Supervisory Control of the Freenove 4WD Car']]],
  ['freenove_204wd_20car_20kit_20—_20peripheral_20summary_27',['Freenove 4WD Car Kit — Peripheral Summary',['../index.html#autotoc_md91',1,'']]],
  ['frequently_20asked_20questions_28',['LambLisp Frequently Asked Questions',['../index.html#faq',1,'']]],
  ['function_20codes_29',['2.3 Function Codes',['../index.html#modbus-function-codes',1,'']]],
  ['function_20codes_20symbols_20for_20modbus_20request_30',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md107',1,'']]],
  ['functions_31',['Functions',['../index.html#autotoc_md106',1,'Controller Functions'],['../index.html#autotoc_md108',1,'Peripheral Functions']]]
];
