var searchData=
[
  ['waypoint_20navigation_0',['3.4 Waypoint Navigation',['../index.html#fwd-nav',1,'']]],
  ['waypoints_20to_20the_20car_1',['4.3 Feeding Waypoints to the Car',['../index.html#fwd-jetson-waypoints',1,'']]],
  ['what_20are_20the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_2',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['what_20happens_20at_20startup_3',['What Happens at Startup',['../index.html#autotoc_md9',1,'']]],
  ['what_20hardware_20does_20lamblisp_20run_20on_4',['What hardware does LambLisp run on?',['../index.html#autotoc_md158',1,'']]],
  ['what_20is_20a_20real_20time_20control_20system_5',['What is a real-time control system?',['../index.html#autotoc_md165',1,'']]],
  ['what_20is_20bytecode_20ncg_20compilation_6',['What is bytecode / NCG compilation?',['../index.html#autotoc_md171',1,'']]],
  ['what_20is_20llip_7',['What is LLIP?',['../index.html#autotoc_md167',1,'']]],
  ['what_20is_20the_20memory_20footprint_8',['What is the memory footprint?',['../index.html#autotoc_md193',1,'']]],
  ['what_20s_20in_20the_20repository_9',['What&apos;s in the repository?',['../index.html#autotoc_md10',1,'']]],
  ['what_20you_20get_10',['1. What You Get',['../index.html#fieldbus-what-you-get',1,'']]],
  ['where_20does_20lamblisp_20sit_20in_20the_20lisp_20landscape_11',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md180',1,'']]],
  ['why_20is_20it_20called_20lamblisp_20instead_20of_20scheme_12',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md176',1,'']]],
  ['why_20it_20exists_13',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['why_20lamblisp_14',['Why &lt;em&gt;LambLisp&lt;/em&gt;?',['../index.html#why-lamblisp',1,'']]],
  ['why_20lisp_15',['Why Lisp?',['../index.html#autotoc_md12',1,'']]],
  ['why_20no_20call_20with_20current_20continuation_16',['Why no &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md178',1,'']]],
  ['why_20not_20use_20embedded_20python_20derivatives_17',['Why not use embedded Python derivatives?',['../index.html#autotoc_md182',1,'']]],
  ['why_20not_20use_20llvm_20for_20native_20code_20generation_18',['Why not use LLVM for native code generation?',['../index.html#autotoc_md184',1,'']]],
  ['why_20the_20compiled_20tier_20does_20not_20run_20on_20embedded_20hardware_19',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md30',1,'']]],
  ['why_20three_20tiers_20',['7.1 Why Three Tiers?',['../index.html#fwd-why-three-tiers',1,'']]],
  ['widely_20recognized_20scheme_20language_20specification_21',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md15',1,'']]],
  ['wifi_22',['WiFi',['../index.html#autotoc_md69',1,'']]],
  ['wifi_20access_20point_20softap_23',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['wifi_20station_20—_20advanced_24',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['wire_25',['I2C (Wire)',['../index.html#autotoc_md68',1,'']]],
  ['wire_20bus_26',['OneWire (1-Wire Bus)',['../index.html#onewire',1,'']]],
  ['wire_20contract_20nvs_27',['The loader wire contract (NVS)',['../index.html#autotoc_md70',1,'']]],
  ['wire_20format_28',['Wire Format',['../index.html#autotoc_md77',1,'']]],
  ['wiring_29',['4. RS-485 Wiring',['../index.html#profibus-wiring',1,'']]],
  ['with_20c_20c_20code_30',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md189',1,'']]],
  ['with_20c_20c_20on_20micro_20controllers_31',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['with_20c_20code_32',['Runtime collaboration with C++ code',['../index.html#autotoc_md25',1,'']]],
  ['with_20current_20continuation_33',['Why no &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md178',1,'']]],
  ['with_20real_20time_20lamblisp_34',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['with_20the_20freenove_204wd_20car_35',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['without_20an_20rtos_36',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md191',1,'']]],
  ['without_20reboot_37',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md19',1,'']]],
  ['without_20reflashing_38',['How do I update code without reflashing?',['../index.html#autotoc_md162',1,'']]],
  ['work_20—_20deferred_20task_20queue_39',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md40',1,'']]],
  ['worked_20example_3a_20autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_40',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['worked_20example_3a_20supervisory_20control_20of_20the_20freenove_204wd_20car_41',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md85',1,'']]],
  ['worked_20examples_42',['Worked Examples',['../index.html#worked-examples',1,'']]],
  ['world_20pauses_43',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md37',1,'']]],
  ['wrappers_20around_20hierarchical_20dictionaries_44',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md29',1,'']]],
  ['wrappers_20sonar_20scm_45',['Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)',['../index.html#autotoc_md102',1,'']]],
  ['write_20callbacks_46',['3.5 Write Callbacks',['../index.html#modbus-write-callbacks',1,'']]],
  ['ws2812_20addressable_20led_20strip_20neopixel_47',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md90',1,'']]],
  ['ws2812_20scm_48',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md95',1,'']]]
];
