var searchData=
[
  ['a_20—_20reach_0',['Group A — Reach',['../index.html#autotoc_md46',1,'']]],
  ['a_20container_1',['Running LambLisp in a Container',['../index.html#containers',1,'']]],
  ['a_20container_2',['Flashing from a container',['../index.html#flashing-from-a-container',1,'']]],
  ['a_20coverage_20plan_3',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['a_20device_20object_4',['4. Answering as a Device object',['../index.html#bacnet-device',1,'']]],
  ['a_20guard_20that_20means_20has_20a_20socket_20must_20now_20say_20so_5',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md212',1,'']]],
  ['a_20hierarchical_20dictionary_6',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['a_20jetson_20or_20raspberry_20pi_20libgpiod_7',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['a_20master_8',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['a_20note_20on_20host_20compatibility_9',['A note on host compatibility',['../index.html#autotoc_md11',1,'']]],
  ['a_20nutshell_10',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md17',1,'']]],
  ['a_20peripheral_11',['3.1 Opening a Peripheral',['../index.html#modbus-peripheral-open',1,'']]],
  ['a_20pin_12',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['a_20port_13',['How blocking works on a port',['../index.html#port-blocking',1,'']]],
  ['a_20real_20time_20control_20system_14',['What is a real-time control system?',['../index.html#autotoc_md181',1,'']]],
  ['a_20slave_15',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['a_20slow_20computation_20from_20a_20stopped_20one_16',['Telling a slow computation from a stopped one',['../index.html#autotoc_md84',1,'']]],
  ['a_20socket_20must_20now_20say_20so_17',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md212',1,'']]],
  ['a_20stopped_20one_18',['Telling a slow computation from a stopped one',['../index.html#autotoc_md84',1,'']]],
  ['a_20string_20may_20contain_20nul_20and_20string_20length_20is_20the_20authority_19',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md148',1,'']]],
  ['aarch64_20',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['access_20point_20softap_21',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['accessors_22',['3.3 Register Accessors',['../index.html#modbus-register-accessors',1,'']]],
  ['accumulator_20floor_20map_20scm_23',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['acknowledgements_24',['Acknowledgements',['../index.html#autotoc_md210',1,'']]],
  ['actually_20drives_20a_20pin_25',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['adaptive_20real_20time_20garbage_20collection_26',['Adaptive real-time garbage collection',['../index.html#autotoc_md23',1,'']]],
  ['addressable_20led_20strip_20neopixel_27',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md100',1,'']]],
  ['addressable_20leds_20ws2812_20scm_28',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md105',1,'']]],
  ['advanced_29',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_30',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md203',1,'']]],
  ['ai_20and_20machine_20to_20machine_31',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['ai_20orchestration_20and_20the_20robot_20stack_32',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['air_20updates_33',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['air_20updates_20without_20reboot_34',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['algebra_35',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['all_20platforms_36',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md189',1,'']]],
  ['already_20inside_37',['The documentation is already inside',['../index.html#autotoc_md9',1,'']]],
  ['already_20rooted_20for_20you_38',['What is already rooted for you',['../index.html#autotoc_md64',1,'']]],
  ['an_20embedded_20board_39',['Flash an embedded board',['../index.html#package-flash',1,'']]],
  ['an_20rtos_40',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md207',1,'']]],
  ['and_20aarch64_41',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['and_20arq_20llip_20serial_20scm_42',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['and_20ascii_20render_43',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['and_20boards_44',['Supported Platforms and Boards',['../index.html#supported-platforms',1,'']]],
  ['and_20c_20api_45',['Language Internals and C++ API',['../index.html#autotoc_md53',1,'']]],
  ['and_20char_20ready_46',['&lt;span class=&quot;tt&quot;&gt;u8-ready?&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;char-ready?&lt;/span&gt;',['../index.html#autotoc_md164',1,'']]],
  ['and_20collisions_47',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['and_20conformance_48',['Language and Conformance',['../index.html#autotoc_md191',1,'']]],
  ['and_20conformance_49',['1. Overview and conformance',['../index.html#bacnet-overview',1,'']]],
  ['and_20development_20tools_50',['Diagnostics and Development Tools',['../index.html#autotoc_md76',1,'']]],
  ['and_20discovery_51',['2. Sessions and discovery',['../index.html#bacnet-discovery',1,'']]],
  ['and_20evaluation_52',['Environments and Evaluation',['../index.html#autotoc_md156',1,'']]],
  ['and_20flash_53',['Build and Flash',['../index.html#autotoc_md15',1,'']]],
  ['and_20gc_20tuning_54',['and GC Tuning',['../index.html#arch-adaptive',1,'Memory and GC Tuning'],['../index.html#gc-tuning',1,'Runtime and GC Tuning']]],
  ['and_20global_20control_55',['2.5 Diagnostics and Global Control',['../index.html#profibus-diag',1,'']]],
  ['and_20hashing_20details_56',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['and_20limits_57',['5. Requirements and limits',['../index.html#bacnet-limits',1,'']]],
  ['and_20list_20structures_58',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['and_20lists_59',['Pairs and Lists',['../index.html#autotoc_md143',1,'']]],
  ['and_20machine_20to_20machine_60',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['and_20macro_61',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['and_20memory_20tuning_62',['GC and memory tuning',['../index.html#autotoc_md85',1,'']]],
  ['and_20motors_20pca9685_20scm_63',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md104',1,'']]],
  ['and_20naming_64',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['and_20non_20symbol_20keys_65',['Objects and non-symbol keys',['../index.html#autotoc_md61',1,'']]],
  ['and_20on_20board_20display_20esp32_20s3_20eye_66',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['and_20operation_67',['Integration and Operation',['../index.html#autotoc_md202',1,'']]],
  ['and_20output_68',['Input and Output',['../index.html#autotoc_md160',1,'']]],
  ['and_20pre_20reserve_69',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['and_20profinet_20interface_70',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['and_20scheme_71',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['and_20scm_20are_20not_20the_20same_20thing_72',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['and_20start_20the_20car_73',['6.2 Flash and Start the Car',['../index.html#fwd-run-car',1,'']]],
  ['and_20string_20length_20is_20the_20authority_74',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md148',1,'']]],
  ['and_20system_75',['Timing and system',['../index.html#autotoc_md83',1,'']]],
  ['and_20tail_20calls_76',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['and_20the_20meaning_20of_200_77',['The bulk form, and the meaning of &lt;span class=&quot;tt&quot;&gt;0&lt;/span&gt;',['../index.html#autotoc_md162',1,'']]],
  ['and_20the_20robot_20stack_78',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['and_20what_20actually_20drives_20a_20pin_79',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['and_20what_20is_20not_80',['and what is not',['../index.html#autotoc_md8',1,'What is in the image, and what is not'],['../index.html#autotoc_md6',1,'What is the same as Linux, and what is not']]],
  ['and_20why_20it_20exists_81',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['and_20writing_20properties_82',['3. Reading and writing properties',['../index.html#bacnet-properties',1,'']]],
  ['answering_20as_20a_20device_20object_83',['4. Answering as a Device object',['../index.html#bacnet-device',1,'']]],
  ['any_20directory_84',['Running from any directory',['../index.html#autotoc_md5',1,'']]],
  ['api_85',['API',['../index.html#profinet-api',1,'5.2 The API'],['../index.html#autotoc_md53',1,'Language Internals and C++ API']]],
  ['api_20for_20new_20lisp_20primitives_86',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#open-api',1,'']]],
  ['api_20llip_20client_20scm_87',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md91',1,'']]],
  ['applications_20as_20virtual_20machines_88',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['arbitrary_20precision_20integers_20bignums_89',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['architecture_90',['Role in the Supervisory Architecture',['../index.html#autotoc_md94',1,'']]],
  ['architecture_20internals_91',['LambLisp Architecture Internals',['../index.html#autotoc_md32',1,'']]],
  ['architecture_20notes_92',['7. Architecture Notes',['../index.html#fwd-arch-notes',1,'']]],
  ['arduino_20embedded_20i_20o_93',['Arduino / Embedded I/O',['../index.html#llarduino',1,'']]],
  ['arduino_20libraries_94',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md22',1,'']]],
  ['are_20first_20class_20data_20types_95',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]],
  ['are_20not_20the_20same_20thing_96',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['are_20porting_20from_20chez_97',['If you are porting from Chez',['../index.html#autotoc_md163',1,'']]],
  ['are_20the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_98',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md203',1,'']]],
  ['are_20wrappers_20around_20hierarchical_20dictionaries_99',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['around_20hierarchical_20dictionaries_100',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['arq_20llip_20serial_20scm_101',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['array_102',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['array_20math_20linear_20algebra_103',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['arrays_20array_104',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['as_20a_20device_20object_105',['4. Answering as a Device object',['../index.html#bacnet-device',1,'']]],
  ['as_20a_20master_106',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['as_20a_20slave_107',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['as_20linux_20and_20what_20is_20not_108',['What is the same as Linux, and what is not',['../index.html#autotoc_md6',1,'']]],
  ['as_20modbus_20controller_109',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['as_20modbus_20peripheral_110',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['as_20the_20universal_20glue_111',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['as_20virtual_20machines_112',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['ascii_20render_113',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['asked_20questions_114',['LambLisp Frequently Asked Questions',['../index.html#faq',1,'']]],
  ['ast_20→_20bytecode_20→_20native_20code_115',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['asynchronous_20work_20—_20deferred_20task_20queue_116',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md45',1,'']]],
  ['at_20startup_117',['What Happens at Startup',['../index.html#startup',1,'']]],
  ['authority_118',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md148',1,'']]],
  ['autonomous_20fill_20behaviour_119',['3.3 Autonomous Fill Behaviour',['../index.html#fwd-autonomous',1,'']]],
  ['autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_120',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]]
];
