var searchData=
[
  ['table_20and_20hashing_20details_0',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['table_20sizing_20and_20collisions_1',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['tables_2',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['tags_3',['Error tags',['../index.html#autotoc_md122',1,'']]],
  ['tail_20calls_4',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['tail_20recursion_20and_20tail_20calls_5',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['talk_20to_20the_20board_6',['Talk to the board',['../index.html#package-connect',1,'']]],
  ['task_20constructors_7',['Task Constructors',['../index.html#autotoc_md113',1,'']]],
  ['task_20queue_8',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md45',1,'']]],
  ['tcp_20tls_20vs_20serial_9',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['telemetry_20floor_20mapping_20demo_20telemetry_20scm_10',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md125',1,'']]],
  ['telemetry_20scm_11',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md125',1,'']]],
  ['telling_20a_20slow_20computation_20from_20a_20stopped_20one_12',['Telling a slow computation from a stopped one',['../index.html#autotoc_md84',1,'']]],
  ['that_20can_20throw_13',['Procedures that can throw',['../index.html#autotoc_md67',1,'']]],
  ['that_20means_20has_20a_20socket_20must_20now_20say_20so_14',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md212',1,'']]],
  ['the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_15',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md203',1,'']]],
  ['the_20air_20updates_16',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['the_20air_20updates_20without_20reboot_17',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['the_20api_18',['5.2 The API',['../index.html#profinet-api',1,'']]],
  ['the_20authority_19',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md148',1,'']]],
  ['the_20baud_20ceiling_20and_20why_20it_20exists_20',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['the_20blocking_20procedures_21',['The blocking procedures',['../index.html#autotoc_md161',1,'']]],
  ['the_20board_22',['Talk to the board',['../index.html#package-connect',1,'']]],
  ['the_20boot_20confirm_20rollback_20model_23',['The boot-confirm / rollback model',['../index.html#autotoc_md80',1,'']]],
  ['the_20bulk_20form_20and_20the_20meaning_20of_200_24',['The bulk form, and the meaning of &lt;span class=&quot;tt&quot;&gt;0&lt;/span&gt;',['../index.html#autotoc_md162',1,'']]],
  ['the_20bus_25',['2.1 Opening the Bus',['../index.html#profibus-open',1,'']]],
  ['the_20car_26',['the Car',['../index.html#fwd-jetson-waypoints',1,'4.3 Feeding Waypoints to the Car'],['../index.html#fwd-run-car',1,'6.2 Flash and Start the Car']]],
  ['the_20cloud_20server_27',['6.1 Start the Cloud Server',['../index.html#fwd-run-cloud',1,'']]],
  ['the_20compiled_20tier_20does_20not_20run_20on_20embedded_20hardware_28',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['the_20daemon_29',['5.1 Building the daemon',['../index.html#profinet-two-processes',1,'']]],
  ['the_20dictionary_20type_30',['The &lt;em&gt;dictionary&lt;/em&gt; type',['../index.html#arch-dict',1,'']]],
  ['the_20documentation_20is_20already_20inside_31',['The documentation is already inside',['../index.html#autotoc_md9',1,'']]],
  ['the_20eval_20operation_32',['The eval Operation',['../index.html#autotoc_md90',1,'']]],
  ['the_20example_33',['the Example',['../index.html#fwd-run',1,'6. Running the Example'],['../index.html#fwd-extend',1,'7.3 Extending the Example']]],
  ['the_20four_20register_20tables_34',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['the_20freenove_204wd_20car_35',['the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car'],['../index.html#autotoc_md95',1,'Worked Example: Supervisory Control of the Freenove 4WD Car']]],
  ['the_20full_20image_36',['Building your own &lt;em&gt;LambLisp&lt;/em&gt;: the &lt;span class=&quot;tt&quot;&gt;full&lt;/span&gt; image',['../index.html#container-full',1,'']]],
  ['the_20image_37',['Which release is in the image',['../index.html#autotoc_md10',1,'']]],
  ['the_20image_20and_20what_20is_20not_38',['What is in the image, and what is not',['../index.html#autotoc_md8',1,'']]],
  ['the_20jetson_39',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['the_20language_40',['Try the language',['../index.html#autotoc_md7',1,'']]],
  ['the_20lisp_20landscape_41',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md196',1,'']]],
  ['the_20loader_20wire_20contract_20nvs_42',['The loader wire contract (NVS)',['../index.html#autotoc_md79',1,'']]],
  ['the_20macro_20cannot_20enforce_43',['Two rules the macro cannot enforce',['../index.html#autotoc_md66',1,'']]],
  ['the_20map_44',['4.5 Collecting the Map',['../index.html#fwd-jetson-collect',1,'']]],
  ['the_20meaning_20of_200_45',['The bulk form, and the meaning of &lt;span class=&quot;tt&quot;&gt;0&lt;/span&gt;',['../index.html#autotoc_md162',1,'']]],
  ['the_20memory_20footprint_46',['What is the memory footprint?',['../index.html#autotoc_md209',1,'']]],
  ['the_20non_20blocking_20request_20poll_20model_47',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['the_20numeric_20tower_48',['The Numeric Tower',['../index.html#autotoc_md137',1,'']]],
  ['the_20oblist_49',['The oblist',['../index.html#autotoc_md60',1,'']]],
  ['the_20package_50',['the package',['../index.html#package-contents',1,'What is in the package'],['../index.html#whats-in-the-package',1,'What&apos;s in the package?']]],
  ['the_20package_20you_20received_51',['Quick Start: The Package You Received',['../index.html#quick-start-package',1,'']]],
  ['the_20queue_52',['The Queue',['../index.html#autotoc_md114',1,'']]],
  ['the_20repl_53',['the REPL',['../index.html#autotoc_md16',1,'Connect to the REPL'],['../index.html#autotoc_md12',1,'Using the REPL']]],
  ['the_20robot_20stack_54',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['the_20same_20as_20linux_20and_20what_20is_20not_55',['What is the same as Linux, and what is not',['../index.html#autotoc_md6',1,'']]],
  ['the_20same_20scheme_20code_20run_20on_20all_20platforms_56',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md189',1,'']]],
  ['the_20same_20thing_57',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['the_20serve_20loop_58',['3.4 The Serve Loop',['../index.html#modbus-serve-loop',1,'']]],
  ['the_20service_20loop_59',['2.3 The Service Loop',['../index.html#profibus-loop',1,'']]],
  ['the_20supervisor_20on_20the_20jetson_60',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['the_20supervisory_20architecture_61',['Role in the Supervisory Architecture',['../index.html#autotoc_md94',1,'']]],
  ['the_20universal_20glue_62',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['the_20world_20pauses_63',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['these_20run_20and_20what_20actually_20drives_20a_20pin_64',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['thing_65',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['three_20states_66',['Which ports have three states',['../index.html#autotoc_md165',1,'']]],
  ['three_20tiers_67',['7.1 Why Three Tiers?',['../index.html#fwd-why-three-tiers',1,'']]],
  ['throw_68',['Procedures that can throw',['../index.html#autotoc_md67',1,'']]],
  ['tier_20does_20not_20run_20on_20embedded_20hardware_69',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['tiers_70',['7.1 Why Three Tiers?',['../index.html#fwd-why-three-tiers',1,'']]],
  ['tiers_3a_20ast_20→_20bytecode_20→_20native_20code_71',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['time_20—_20bounded_20control_20cycle_72',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md43',1,'']]],
  ['time_20compilation_73',['Incremental, just-in-time compilation',['../index.html#autotoc_md26',1,'']]],
  ['time_20control_74',['Real-time control',['../index.html#autotoc_md19',1,'']]],
  ['time_20control_20system_75',['What is a real-time control system?',['../index.html#autotoc_md181',1,'']]],
  ['time_20garbage_20collection_76',['Adaptive real-time garbage collection',['../index.html#autotoc_md23',1,'']]],
  ['time_20guarantees_77',['Real-time Guarantees',['../index.html#arch-realtime',1,'']]],
  ['time_20lamblisp_78',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['time_20lisp_20for_20microprocessors_79',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['time_20sntp_80',['Network Time (SNTP)',['../index.html#nettime',1,'']]],
  ['timers_20scm_81',['Timers (&lt;span class=&quot;tt&quot;&gt;Timers.scm&lt;/span&gt;)',['../index.html#autotoc_md108',1,'']]],
  ['timers_20timers_20scm_82',['Timers (&lt;span class=&quot;tt&quot;&gt;Timers.scm&lt;/span&gt;)',['../index.html#autotoc_md108',1,'']]],
  ['timing_20and_20system_83',['Timing and system',['../index.html#autotoc_md83',1,'']]],
  ['tls_20vs_20serial_84',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['to_20esp32_85',['Deploy to ESP32',['../index.html#deploy-esp32',1,'']]],
  ['to_20machine_86',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['to_20the_20board_87',['Talk to the board',['../index.html#package-connect',1,'']]],
  ['to_20the_20car_88',['4.3 Feeding Waypoints to the Car',['../index.html#fwd-jetson-waypoints',1,'']]],
  ['to_20the_20repl_89',['Connect to the REPL',['../index.html#autotoc_md16',1,'']]],
  ['tools_90',['Diagnostics and Development Tools',['../index.html#autotoc_md76',1,'']]],
  ['tools_20llip_91',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['tower_92',['The Numeric Tower',['../index.html#autotoc_md137',1,'']]],
  ['transport_20and_20arq_20llip_20serial_20scm_93',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['transport_20scm_94',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['transports_3a_20tcp_20tls_20vs_20serial_95',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['try_20lamblisp_20in_20your_20browser_96',['Quick Start: Try LambLisp in Your Browser',['../index.html#quick-start-browser',1,'']]],
  ['try_20lamblisp_20on_20linux_97',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['try_20lamblisp_20on_20windows_98',['Quick Start: Try LambLisp on Windows',['../index.html#quick-start-windows',1,'']]],
  ['try_20lamblisp_20right_20now_99',['How do I try LambLisp right now?',['../index.html#autotoc_md172',1,'']]],
  ['try_20the_20language_100',['Try the language',['../index.html#autotoc_md7',1,'']]],
  ['tuning_101',['Tuning',['../index.html#arch-adaptive',1,'Memory and GC Tuning'],['../index.html#gc-tuning',1,'Runtime and GC Tuning']]],
  ['tuning_102',['GC and memory tuning',['../index.html#autotoc_md85',1,'']]],
  ['tuning_20parameters_103',['6.4 Tuning Parameters',['../index.html#fwd-run-tuning',1,'']]],
  ['tuning_3a_20stack_20size_20dma_20memory_20and_20pre_20reserve_104',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['twin_105',['Digital Twin',['../index.html#autotoc_md96',1,'']]],
  ['twin_20sync_106',['4.4 Digital Twin Sync',['../index.html#fwd-jetson-twin',1,'']]],
  ['two_20rules_20the_20macro_20cannot_20enforce_107',['Two rules the macro cannot enforce',['../index.html#autotoc_md66',1,'']]],
  ['type_108',['The &lt;em&gt;dictionary&lt;/em&gt; type',['../index.html#arch-dict',1,'']]],
  ['type_20system_109',['Type System',['../index.html#autotoc_md135',1,'']]],
  ['typed_20numeric_20arrays_20array_110',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['types_111',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]]
];
