var searchData=
[
  ['s_20in_20the_20repository_0',['What&apos;s in the repository?',['../index.html#autotoc_md10',1,'']]],
  ['s3_1',['4.2 ESP32-S3',['../index.html#modbus-esp32',1,'']]],
  ['s3_20eye_2',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['same_20scheme_20code_20run_20on_20all_20platforms_3',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md173',1,'']]],
  ['sandbox_20demo_20sandbox_20scm_4',['Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)',['../index.html#autotoc_md114',1,'']]],
  ['sandbox_20scm_5',['Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)',['../index.html#autotoc_md114',1,'']]],
  ['scalability_6',['Scalability',['../index.html#arch-scalability',1,'']]],
  ['scheduling_7',['Behaviors: Cooperative Scheduling',['../index.html#behaviors',1,'']]],
  ['scheme_8',['Scheme',['../index.html#arch-history',1,'Brief history of Lisp and Scheme'],['../index.html#autotoc_md176',1,'Why is it called LambLisp instead of Scheme?']]],
  ['scheme_20code_20run_20on_20all_20platforms_9',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md173',1,'']]],
  ['scheme_20implementations_10',['Other Scheme Implementations',['../index.html#competitors',1,'']]],
  ['scheme_20language_20specification_11',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md15',1,'']]],
  ['scheme_20libraries_12',['Bundled Scheme Libraries',['../index.html#scheme-libraries',1,'']]],
  ['scm_13',['scm',['../index.html#fwd-floor-map-scm',1,'3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)'],['../index.html#autotoc_md95',1,'Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)'],['../index.html#autotoc_md97',1,'Buzzer (&lt;span class=&quot;tt&quot;&gt;Buzzer.scm&lt;/span&gt;)'],['../index.html#autotoc_md81',1,'Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)'],['../index.html#llip-device-serve',1,'Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)'],['../index.html#autotoc_md114',1,'Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)'],['../index.html#llip-http',1,'HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)'],['../index.html#autotoc_md101',1,'I2C Bus Utilities (&lt;span class=&quot;tt&quot;&gt;I2C.scm&lt;/span&gt;)'],['../index.html#autotoc_md99',1,'I2C GPIO Expander (&lt;span class=&quot;tt&quot;&gt;PCF8574.scm&lt;/span&gt;)'],['../index.html#autotoc_md96',1,'LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)'],['../index.html#autotoc_md100',1,'Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)'],['../index.html#autotoc_md116',1,'Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)'],['../index.html#autotoc_md117',1,'Personality (&lt;span class=&quot;tt&quot;&gt;Personality.scm&lt;/span&gt;)'],['../index.html#llip-serial',1,'Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)'],['../index.html#autotoc_md82',1,'Server (&lt;span class=&quot;tt&quot;&gt;llip-server.scm&lt;/span&gt;)'],['../index.html#autotoc_md94',1,'Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)'],['../index.html#autotoc_md102',1,'Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)'],['../index.html#autotoc_md113',1,'Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)'],['../index.html#autotoc_md115',1,'Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)'],['../index.html#autotoc_md98',1,'Timers (&lt;span class=&quot;tt&quot;&gt;Timers.scm&lt;/span&gt;)']]],
  ['scm_20live_20preview_20layer_14',['eye-cam.scm live-preview layer',['../index.html#autotoc_md93',1,'']]],
  ['scoping_15',['Lexical scoping',['../index.html#autotoc_md22',1,'']]],
  ['security_16',['Security',['../index.html#autotoc_md83',1,'']]],
  ['sensor_20lightsensor_20scm_17',['Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)',['../index.html#autotoc_md100',1,'']]],
  ['serial_18',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['serial_20scm_19',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['serial_20transport_20and_20arq_20llip_20serial_20scm_20',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['serve_20loop_21',['3.4 The Serve Loop',['../index.html#modbus-serve-loop',1,'']]],
  ['server_22',['Server',['../index.html#fwd-cloud',1,'5. Cloud Strategy Server'],['../index.html#fwd-cloud-bee',1,'5.3 Bee Strategy Server'],['../index.html#fwd-run-cloud',1,'6.1 Start the Cloud Server']]],
  ['server_20llip_20server_20scm_23',['Server (&lt;span class=&quot;tt&quot;&gt;llip-server.scm&lt;/span&gt;)',['../index.html#autotoc_md82',1,'']]],
  ['server_20scm_24',['Server (&lt;span class=&quot;tt&quot;&gt;llip-server.scm&lt;/span&gt;)',['../index.html#autotoc_md82',1,'']]],
  ['service_20leds_20scm_25',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md96',1,'']]],
  ['service_20loop_26',['2.3 The Service Loop',['../index.html#profibus-loop',1,'']]],
  ['serving_20llip_20transport_20scm_27',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['servos_20and_20motors_20pca9685_20scm_28',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md94',1,'']]],
  ['setup_29',['2. Hardware Setup',['../index.html#fwd-hw',1,'']]],
  ['sit_20in_20the_20lisp_20landscape_30',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md180',1,'']]],
  ['size_20dma_20memory_20and_20pre_20reserve_31',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['sizing_20and_20collisions_32',['Hash table sizing and collisions',['../index.html#autotoc_md54',1,'']]],
  ['slave_33',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['slave_34',['PROFIBUS DP slave',['../index.html#autotoc_md110',1,'']]],
  ['slaves_35',['2.2 Declaring Slaves',['../index.html#profibus-add-slave',1,'']]],
  ['softap_36',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['sonar_20convenience_20wrappers_20sonar_20scm_37',['Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)',['../index.html#autotoc_md102',1,'']]],
  ['sonar_20hc_20sr04_38',['Ultrasonic Sonar (HC-SR04)',['../index.html#ultrasonic-sonar-hc-sr04',1,'']]],
  ['sonar_20scm_39',['Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)',['../index.html#autotoc_md102',1,'']]],
  ['source_40',['Is LambLisp open source?',['../index.html#autotoc_md160',1,'']]],
  ['specification_41',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md15',1,'']]],
  ['speed_42',['Group B — Speed',['../index.html#autotoc_md44',1,'']]],
  ['spi_20bus_43',['SPI Bus',['../index.html#spi',1,'']]],
  ['sr04_44',['Ultrasonic Sonar (HC-SR04)',['../index.html#ultrasonic-sonar-hc-sr04',1,'']]],
  ['stack_45',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['stack_20size_20dma_20memory_20and_20pre_20reserve_46',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['start_20the_20car_47',['6.2 Flash and Start the Car',['../index.html#fwd-run-car',1,'']]],
  ['start_20the_20cloud_20server_48',['6.1 Start the Cloud Server',['../index.html#fwd-run-cloud',1,'']]],
  ['start_3a_20try_20lamblisp_20on_20linux_49',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['started_50',['Getting Started',['../index.html#autotoc_md155',1,'']]],
  ['started_20with_20real_20time_20lamblisp_51',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['startup_52',['What Happens at Startup',['../index.html#autotoc_md9',1,'']]],
  ['stateful_20objects_53',['Stateful Objects',['../index.html#autotoc_md59',1,'']]],
  ['stateless_20procedures_54',['Stateless Procedures',['../index.html#arch-mop3',1,'']]],
  ['station_20—_20advanced_55',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['stop_20the_20world_20pauses_56',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md37',1,'']]],
  ['store_20and_20ascii_20render_57',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['strategy_20module_58',['3.5 Bee Strategy Module',['../index.html#fwd-bee-onboard',1,'']]],
  ['strategy_20server_59',['Strategy Server',['../index.html#fwd-cloud',1,'5. Cloud Strategy Server'],['../index.html#fwd-cloud-bee',1,'5.3 Bee Strategy Server']]],
  ['strings_60',['Strings',['../index.html#autotoc_md137',1,'']]],
  ['strip_20neopixel_61',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md90',1,'']]],
  ['struct_62',['Binary framing (struct)',['../index.html#struct',1,'']]],
  ['structured_20data_63',['Structured Data',['../index.html#structured-data',1,'']]],
  ['structures_64',['Cell Memory Model and List Structures',['../index.html#autotoc_md36',1,'']]],
  ['sub_20microsecond_20isr_65',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md39',1,'']]],
  ['summary_66',['Summary',['../index.html#modbus-build-flags',1,'4.3 Build Flag Summary'],['../index.html#autotoc_md120',1,'Coverage Summary'],['../index.html#autotoc_md91',1,'Freenove 4WD Car Kit — Peripheral Summary']]],
  ['summary_67',['Key feature summary',['../index.html#autotoc_md26',1,'']]],
  ['supervisor_68',['4. Jetson Supervisor',['../index.html#fwd-jetson',1,'']]],
  ['supervisor_20on_20the_20jetson_69',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['supervisor_20scm_70',['Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)',['../index.html#autotoc_md113',1,'']]],
  ['supervisory_20architecture_71',['Role in the Supervisory Architecture',['../index.html#autotoc_md84',1,'']]],
  ['supervisory_20control_20demo_20supervisor_20scm_72',['Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)',['../index.html#autotoc_md113',1,'']]],
  ['supervisory_20control_20of_20the_20freenove_204wd_20car_73',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md85',1,'']]],
  ['support_74',['Multi-Platform Support',['../index.html#arch-multiplatform',1,'']]],
  ['supported_20platforms_20and_20boards_75',['Supported Platforms and Boards',['../index.html#autotoc_md4',1,'']]],
  ['symbol_20keys_76',['Objects and non-symbol keys',['../index.html#autotoc_md56',1,'']]],
  ['symbols_77',['Symbols',['../index.html#autotoc_md131',1,'']]],
  ['symbols_20for_20modbus_20request_78',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md107',1,'']]],
  ['sync_79',['4.4 Digital Twin Sync',['../index.html#fwd-jetson-twin',1,'']]],
  ['syntax_20forms_80',['Syntax Forms',['../index.html#autotoc_md61',1,'']]],
  ['system_81',['System',['../index.html#autotoc_md105',1,'ESP32 System'],['../index.html#autotoc_md125',1,'Type System']]],
  ['system_82',['system',['../index.html#autotoc_md57',1,'Lightweight object system'],['../index.html#autotoc_md74',1,'Timing and system'],['../index.html#autotoc_md165',1,'What is a real-time control system?']]],
  ['system_20interface_83',['System Interface',['../index.html#autotoc_md151',1,'']]]
];
