var searchData=
[
  ['reach_0',['Reach',['../index.html#autotoc_md41',1,'Group A — Reach'],['../index.html#autotoc_md42',1,'Network Reach']]],
  ['real_20time_20control_1',['Real-time control',['../index.html#autotoc_md13',1,'']]],
  ['real_20time_20control_20system_2',['What is a real-time control system?',['../index.html#autotoc_md165',1,'']]],
  ['real_20time_20garbage_20collection_3',['Adaptive real-time garbage collection',['../index.html#autotoc_md17',1,'']]],
  ['real_20time_20guarantees_4',['Real-time Guarantees',['../index.html#arch-realtime',1,'']]],
  ['real_20time_20lamblisp_5',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['real_20time_20lisp_20for_20microprocessors_6',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['reboot_7',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md19',1,'']]],
  ['recognized_20scheme_20language_20specification_8',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md15',1,'']]],
  ['recursion_20and_20tail_20calls_9',['Tail recursion and tail-calls',['../index.html#autotoc_md23',1,'']]],
  ['reference_10',['Reference',['../index.html#modbus-quickref',1,'5. Quick Reference'],['../index.html#fieldbus-quickref',1,'8. Quick Reference']]],
  ['reflashing_11',['How do I update code without reflashing?',['../index.html#autotoc_md162',1,'']]],
  ['register_20accessors_12',['3.3 Register Accessors',['../index.html#modbus-register-accessors',1,'']]],
  ['register_20tables_13',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['reload_14',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['render_15',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['repl_16',['REPL',['../index.html#autotoc_md8',1,'Connect to the REPL'],['../index.html#autotoc_md3',1,'Using the REPL']]],
  ['repository_17',['What&apos;s in the repository?',['../index.html#autotoc_md10',1,'']]],
  ['request_18',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md107',1,'']]],
  ['request_20poll_20model_19',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['requesting_20a_20coverage_20plan_20',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['reserve_21',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['reuse_20of_20existing_20c_20arduino_20libraries_22',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md16',1,'']]],
  ['right_20now_23',['How do I try LambLisp right now?',['../index.html#autotoc_md156',1,'']]],
  ['ring_20service_20leds_20scm_24',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md96',1,'']]],
  ['robot_20stack_25',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['role_20in_20the_20supervisory_20architecture_26',['Role in the Supervisory Architecture',['../index.html#autotoc_md84',1,'']]],
  ['rollback_20model_27',['The boot-confirm / rollback model',['../index.html#autotoc_md71',1,'']]],
  ['rs_20485_20wiring_28',['4. RS-485 Wiring',['../index.html#profibus-wiring',1,'']]],
  ['rtos_29',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md191',1,'']]],
  ['run_20on_30',['What hardware does LambLisp run on?',['../index.html#autotoc_md158',1,'']]],
  ['run_20on_20all_20platforms_31',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md173',1,'']]],
  ['run_20on_20embedded_20hardware_32',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md30',1,'']]],
  ['run_20the_20supervisor_20on_20the_20jetson_33',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['running_20the_20example_34',['6. Running the Example',['../index.html#fwd-run',1,'']]],
  ['runtime_20and_20gc_20tuning_35',['Runtime and GC Tuning',['../index.html#gc-tuning',1,'']]],
  ['runtime_20collaboration_20with_20c_20code_36',['Runtime collaboration with C++ code',['../index.html#autotoc_md25',1,'']]]
];
