var searchData=
[
  ['lambda_0',['lambda',['../index.html#autotoc_md49',1,'']]],
  ['lambda_20nlambda_20and_20macro_1',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['lamblisp_2',['LambLisp',['../index.html#autotoc_md1',1,'Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;'],['../index.html#autotoc_md169',1,'How fast is LambLisp?'],['../index.html#why-lamblisp',1,'Why &lt;em&gt;LambLisp&lt;/em&gt;?']]],
  ['lamblisp_20architecture_20internals_3',['LambLisp Architecture Internals',['../index.html#autotoc_md27',1,'']]],
  ['lamblisp_20as_20modbus_20controller_4',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['lamblisp_20as_20modbus_20peripheral_5',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['lamblisp_20block_20diagram_6',['LambLisp Block Diagram',['../index.html#autotoc_md33',1,'']]],
  ['lamblisp_20compatibility_20matrix_7',['LambLisp Compatibility Matrix',['../index.html#compat-matrix',1,'']]],
  ['lamblisp_20extensions_8',['LambLisp Extensions',['../index.html#autotoc_md64',1,'']]],
  ['lamblisp_20frequently_20asked_20questions_9',['LambLisp Frequently Asked Questions',['../index.html#faq',1,'']]],
  ['lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_10',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['lamblisp_20instead_20of_20scheme_11',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md176',1,'']]],
  ['lamblisp_20interaction_20protocol_12',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['lamblisp_20interoperate_20with_20c_20c_20code_13',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md189',1,'']]],
  ['lamblisp_20modbus_20interface_14',['LambLisp Modbus Interface',['../index.html#modbus',1,'']]],
  ['lamblisp_20on_20linux_15',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['lamblisp_20open_20source_16',['Is LambLisp open source?',['../index.html#autotoc_md160',1,'']]],
  ['lamblisp_20profibus_20and_20profinet_20interface_17',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['lamblisp_20right_20now_18',['How do I try LambLisp right now?',['../index.html#autotoc_md156',1,'']]],
  ['lamblisp_20run_20on_19',['What hardware does LambLisp run on?',['../index.html#autotoc_md158',1,'']]],
  ['lamblisp_20sit_20in_20the_20lisp_20landscape_20',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md180',1,'']]],
  ['lamblisp_20virtual_20machine_21',['LambLisp Virtual Machine',['../index.html#autotoc_md31',1,'']]],
  ['lamblisp_20without_20an_20rtos_22',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md191',1,'']]],
  ['landscape_23',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md180',1,'']]],
  ['language_24',['Core Language',['../index.html#autotoc_md123',1,'']]],
  ['language_20and_20conformance_25',['Language and Conformance',['../index.html#autotoc_md175',1,'']]],
  ['language_20extensions_26',['Language Extensions',['../index.html#language-extensions',1,'']]],
  ['language_20internals_20and_20c_20api_27',['Language Internals and C++ API',['../index.html#autotoc_md48',1,'']]],
  ['language_20specification_28',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md15',1,'']]],
  ['latency_20—_20no_20stop_20the_20world_20pauses_29',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md37',1,'']]],
  ['latency_20—_20sub_20microsecond_20isr_30',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md39',1,'']]],
  ['layer_31',['eye-cam.scm live-preview layer',['../index.html#autotoc_md93',1,'']]],
  ['layer_20llip_20http_20scm_32',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['lcd_20primitives_20c_33',['Camera / LCD primitives (C++)',['../index.html#autotoc_md92',1,'']]],
  ['lcd1602_20display_34',['LCD1602 Display',['../index.html#autotoc_md88',1,'']]],
  ['led_20ring_20service_20leds_20scm_35',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md96',1,'']]],
  ['led_20strip_20neopixel_36',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md90',1,'']]],
  ['leds_20scm_37',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md96',1,'']]],
  ['leds_20ws2812_20scm_38',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md95',1,'']]],
  ['legend_39',['Legend',['../index.html#autotoc_md118',1,'']]],
  ['lexical_20scoping_40',['Lexical scoping',['../index.html#autotoc_md22',1,'']]],
  ['libraries_41',['Bundled Scheme Libraries',['../index.html#scheme-libraries',1,'']]],
  ['libraries_42',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md16',1,'']]],
  ['license_43',['License',['../index.html#license',1,'']]],
  ['lifecycle_44',['Connection Lifecycle',['../index.html#autotoc_md78',1,'']]],
  ['lifecycle_3a_20incremental_20hot_20reload_45',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['light_20sensor_20lightsensor_20scm_46',['Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)',['../index.html#autotoc_md100',1,'']]],
  ['lightsensor_20scm_47',['Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)',['../index.html#autotoc_md100',1,'']]],
  ['lightweight_20object_20system_48',['Lightweight object system',['../index.html#autotoc_md57',1,'']]],
  ['line_20client_3a_20tools_20llip_49',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['linear_20algebra_50',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['linux_51',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['linux_20jetson_20builds_52',['Linux / Jetson Builds',['../index.html#autotoc_md6',1,'']]],
  ['linux_20x86_5f64_20and_20aarch64_53',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['lisp_54',['Why Lisp?',['../index.html#autotoc_md12',1,'']]],
  ['lisp_20and_20scheme_55',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['lisp_20for_20microprocessors_56',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['lisp_20in_20a_20nutshell_57',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md11',1,'']]],
  ['lisp_20landscape_58',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md180',1,'']]],
  ['lisp_20primitives_59',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md18',1,'']]],
  ['list_20structures_60',['Cell Memory Model and List Structures',['../index.html#autotoc_md36',1,'']]],
  ['lists_61',['Pairs and Lists',['../index.html#autotoc_md133',1,'']]],
  ['live_20preview_20layer_62',['eye-cam.scm live-preview layer',['../index.html#autotoc_md93',1,'']]],
  ['llip_63',['What is LLIP?',['../index.html#autotoc_md167',1,'']]],
  ['llip_64',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['llip_20—_20lamblisp_20interaction_20protocol_65',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['llip_20as_20the_20universal_20glue_66',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['llip_20client_20scm_67',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md81',1,'']]],
  ['llip_20http_20scm_68',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['llip_20serial_20scm_69',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['llip_20server_20scm_70',['Server (&lt;span class=&quot;tt&quot;&gt;llip-server.scm&lt;/span&gt;)',['../index.html#autotoc_md82',1,'']]],
  ['llip_20transport_20scm_71',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['llm_20layer_20llip_20http_20scm_72',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['llvm_20for_20native_20code_20generation_73',['Why not use LLVM for native code generation?',['../index.html#autotoc_md184',1,'']]],
  ['loader_20wire_20contract_20nvs_74',['The loader wire contract (NVS)',['../index.html#autotoc_md70',1,'']]],
  ['loop_75',['Loop',['../index.html#profibus-loop',1,'2.3 The Service Loop'],['../index.html#modbus-serve-loop',1,'3.4 The Serve Loop']]],
  ['loop_20time_20—_20bounded_20control_20cycle_76',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md38',1,'']]]
];
