var searchData=
[
  ['a_20—_20reach_0',['Group A — Reach',['../index.html#autotoc_md41',1,'']]],
  ['a_20coverage_20plan_1',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['a_20hierarchical_20dictionary_2',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['a_20master_3',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['a_20nutshell_4',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md11',1,'']]],
  ['a_20peripheral_5',['3.1 Opening a Peripheral',['../index.html#modbus-peripheral-open',1,'']]],
  ['a_20real_20time_20control_20system_6',['What is a real-time control system?',['../index.html#autotoc_md165',1,'']]],
  ['a_20slave_7',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['aarch64_8',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['access_20point_20softap_9',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['accessors_10',['3.3 Register Accessors',['../index.html#modbus-register-accessors',1,'']]],
  ['accumulator_20floor_20map_20scm_11',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['acknowledgements_12',['Acknowledgements',['../index.html#autotoc_md194',1,'']]],
  ['adaptive_20real_20time_20garbage_20collection_13',['Adaptive real-time garbage collection',['../index.html#autotoc_md17',1,'']]],
  ['addressable_20led_20strip_20neopixel_14',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md90',1,'']]],
  ['addressable_20leds_20ws2812_20scm_15',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md95',1,'']]],
  ['advanced_16',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_17',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['ai_20and_20machine_20to_20machine_18',['AI and Machine-to-Machine',['../index.html#autotoc_md43',1,'']]],
  ['ai_20orchestration_20and_20the_20robot_20stack_19',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['air_20updates_20',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['air_20updates_20without_20reboot_21',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md19',1,'']]],
  ['algebra_22',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['all_20platforms_23',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md173',1,'']]],
  ['an_20rtos_24',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md191',1,'']]],
  ['and_20aarch64_25',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['and_20arq_20llip_20serial_20scm_26',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['and_20ascii_20render_27',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['and_20boards_28',['Supported Platforms and Boards',['../index.html#autotoc_md4',1,'']]],
  ['and_20c_20api_29',['Language Internals and C++ API',['../index.html#autotoc_md48',1,'']]],
  ['and_20collisions_30',['Hash table sizing and collisions',['../index.html#autotoc_md54',1,'']]],
  ['and_20compatible_31',['Arduino / Embedded I/O (ESP32 and compatible)',['../index.html#autotoc_md67',1,'']]],
  ['and_20conformance_32',['Language and Conformance',['../index.html#autotoc_md175',1,'']]],
  ['and_20development_20tools_33',['Diagnostics and Development Tools',['../index.html#autotoc_md66',1,'']]],
  ['and_20evaluation_34',['Environments and Evaluation',['../index.html#autotoc_md145',1,'']]],
  ['and_20flash_35',['Build and Flash',['../index.html#autotoc_md7',1,'']]],
  ['and_20gc_20tuning_36',['and GC Tuning',['../index.html#arch-adaptive',1,'Memory and GC Tuning'],['../index.html#gc-tuning',1,'Runtime and GC Tuning']]],
  ['and_20global_20control_37',['2.5 Diagnostics and Global Control',['../index.html#profibus-diag',1,'']]],
  ['and_20hashing_20details_38',['Hash table and hashing details',['../index.html#autotoc_md53',1,'']]],
  ['and_20list_20structures_39',['Cell Memory Model and List Structures',['../index.html#autotoc_md36',1,'']]],
  ['and_20lists_40',['Pairs and Lists',['../index.html#autotoc_md133',1,'']]],
  ['and_20machine_20to_20machine_41',['AI and Machine-to-Machine',['../index.html#autotoc_md43',1,'']]],
  ['and_20macro_42',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['and_20memory_20tuning_43',['GC and memory tuning',['../index.html#autotoc_md75',1,'']]],
  ['and_20motors_20pca9685_20scm_44',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md94',1,'']]],
  ['and_20naming_45',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['and_20non_20symbol_20keys_46',['Objects and non-symbol keys',['../index.html#autotoc_md56',1,'']]],
  ['and_20on_20board_20display_20esp32_20s3_20eye_47',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['and_20operation_48',['Integration and Operation',['../index.html#autotoc_md186',1,'']]],
  ['and_20output_49',['Input and Output',['../index.html#autotoc_md149',1,'']]],
  ['and_20pre_20reserve_50',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['and_20profinet_20interface_51',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['and_20scheme_52',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['and_20start_20the_20car_53',['6.2 Flash and Start the Car',['../index.html#fwd-run-car',1,'']]],
  ['and_20system_54',['Timing and system',['../index.html#autotoc_md74',1,'']]],
  ['and_20tail_20calls_55',['Tail recursion and tail-calls',['../index.html#autotoc_md23',1,'']]],
  ['and_20the_20robot_20stack_56',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['and_20why_20it_20exists_57',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['api_58',['API',['../index.html#profinet-api',1,'5.2 The API'],['../index.html#autotoc_md48',1,'Language Internals and C++ API']]],
  ['api_20for_20new_20lisp_20primitives_59',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md18',1,'']]],
  ['api_20llip_20client_20scm_60',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md81',1,'']]],
  ['applications_20as_20virtual_20machines_61',['Control Applications as Virtual Machines.',['../index.html#autotoc_md32',1,'']]],
  ['arbitrary_20precision_20integers_20bignums_62',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['architecture_63',['Role in the Supervisory Architecture',['../index.html#autotoc_md84',1,'']]],
  ['architecture_20internals_64',['LambLisp Architecture Internals',['../index.html#autotoc_md27',1,'']]],
  ['architecture_20notes_65',['7. Architecture Notes',['../index.html#fwd-arch-notes',1,'']]],
  ['arduino_20embedded_20i_20o_20esp32_20and_20compatible_66',['Arduino / Embedded I/O (ESP32 and compatible)',['../index.html#autotoc_md67',1,'']]],
  ['arduino_20libraries_67',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md16',1,'']]],
  ['are_20first_20class_20data_20types_68',['Procedures are first-class data types',['../index.html#autotoc_md24',1,'']]],
  ['are_20the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_69',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md187',1,'']]],
  ['are_20wrappers_20around_20hierarchical_20dictionaries_70',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md29',1,'']]],
  ['around_20hierarchical_20dictionaries_71',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md29',1,'']]],
  ['arq_20llip_20serial_20scm_72',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['array_73',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['array_20math_20linear_20algebra_74',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['arrays_20array_75',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['as_20a_20master_76',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['as_20a_20slave_77',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['as_20modbus_20controller_78',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['as_20modbus_20peripheral_79',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['as_20the_20universal_20glue_80',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['as_20virtual_20machines_81',['Control Applications as Virtual Machines.',['../index.html#autotoc_md32',1,'']]],
  ['ascii_20render_82',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['asked_20questions_83',['LambLisp Frequently Asked Questions',['../index.html#faq',1,'']]],
  ['ast_20→_20bytecode_20→_20native_20code_84',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['asynchronous_20work_20—_20deferred_20task_20queue_85',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md40',1,'']]],
  ['at_20startup_86',['What Happens at Startup',['../index.html#autotoc_md9',1,'']]],
  ['autonomous_20fill_20behaviour_87',['3.3 Autonomous Fill Behaviour',['../index.html#fwd-autonomous',1,'']]],
  ['autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_88',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]]
];
