var searchData=
[
  ['pairs_20and_20lists_0',['Pairs and Lists',['../index.html#autotoc_md133',1,'']]],
  ['parameters_1',['6.4 Tuning Parameters',['../index.html#fwd-run-tuning',1,'']]],
  ['patterns_2',['Device Patterns',['../index.html#autotoc_md60',1,'']]],
  ['pauses_3',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md37',1,'']]],
  ['pca9685_20pwm_20controller_4',['PCA9685 PWM Controller',['../index.html#autotoc_md89',1,'']]],
  ['pca9685_20scm_5',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md94',1,'']]],
  ['pcf8574_20scm_6',['I2C GPIO Expander (&lt;span class=&quot;tt&quot;&gt;PCF8574.scm&lt;/span&gt;)',['../index.html#autotoc_md99',1,'']]],
  ['peripheral_7',['Peripheral',['../index.html#modbus-peripheral',1,'3. LambLisp as Modbus Peripheral'],['../index.html#modbus-peripheral-open',1,'3.1 Opening a Peripheral']]],
  ['peripheral_20functions_8',['Peripheral Functions',['../index.html#autotoc_md108',1,'']]],
  ['peripheral_20summary_9',['Freenove 4WD Car Kit — Peripheral Summary',['../index.html#autotoc_md91',1,'']]],
  ['personality_20personality_20scm_10',['Personality (&lt;span class=&quot;tt&quot;&gt;Personality.scm&lt;/span&gt;)',['../index.html#autotoc_md117',1,'']]],
  ['personality_20scm_11',['Personality (&lt;span class=&quot;tt&quot;&gt;Personality.scm&lt;/span&gt;)',['../index.html#autotoc_md117',1,'']]],
  ['plan_12',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['planner_13',['5.1 Boustrophedon Coverage Planner',['../index.html#fwd-cloud-planner',1,'']]],
  ['platform_14',['Multi-platform',['../index.html#autotoc_md14',1,'']]],
  ['platform_20notes_15',['4. Platform Notes',['../index.html#modbus-platform',1,'']]],
  ['platform_20support_16',['Multi-Platform Support',['../index.html#arch-multiplatform',1,'']]],
  ['platforms_17',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md173',1,'']]],
  ['platforms_20and_20boards_18',['Supported Platforms and Boards',['../index.html#autotoc_md4',1,'']]],
  ['point_20softap_19',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['poll_20model_20',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['ports_21',['Ports',['../index.html#autotoc_md147',1,'']]],
  ['pre_20reserve_22',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['precision_20integers_20bignums_23',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['prerequisites_24',['Prerequisites',['../index.html#autotoc_md2',1,'']]],
  ['preview_20layer_25',['eye-cam.scm live-preview layer',['../index.html#autotoc_md93',1,'']]],
  ['primitives_26',['3.2 Motion Primitives',['../index.html#fwd-motion',1,'']]],
  ['primitives_27',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md18',1,'']]],
  ['primitives_20c_28',['Camera / LCD primitives (C++)',['../index.html#autotoc_md92',1,'']]],
  ['procedures_29',['Stateless Procedures',['../index.html#arch-mop3',1,'']]],
  ['procedures_20are_20first_20class_20data_20types_30',['Procedures are first-class data types',['../index.html#autotoc_md24',1,'']]],
  ['profibus_20and_20profinet_20interface_31',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['profibus_20dp_20as_20a_20master_32',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['profibus_20dp_20as_20a_20slave_33',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['profibus_20dp_20master_34',['PROFIBUS DP master',['../index.html#autotoc_md109',1,'']]],
  ['profibus_20dp_20slave_35',['PROFIBUS DP slave',['../index.html#autotoc_md110',1,'']]],
  ['profinet_36',['5. PROFINET',['../index.html#profinet',1,'']]],
  ['profinet_20interface_37',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['profinet_20io_20device_38',['PROFINET IO-Device',['../index.html#autotoc_md111',1,'']]],
  ['proprietary_20distribution_39',['Proprietary Distribution',['../index.html#autotoc_md62',1,'']]],
  ['protocol_40',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['pwm_20controller_41',['PCA9685 PWM Controller',['../index.html#autotoc_md89',1,'']]],
  ['python_20derivatives_42',['Why not use embedded Python derivatives?',['../index.html#autotoc_md182',1,'']]]
];
