var searchData=
[
  ['naming_0',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['native_20code_1',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['native_20code_20generation_2',['Why not use LLVM for native code generation?',['../index.html#autotoc_md184',1,'']]],
  ['native_20code_20generator_20ncg_3',['Native Code Generator (NCG)',['../index.html#arch-ncg',1,'']]],
  ['navigation_4',['3.4 Waypoint Navigation',['../index.html#fwd-nav',1,'']]],
  ['ncg_5',['Native Code Generator (NCG)',['../index.html#arch-ncg',1,'']]],
  ['ncg_20compilation_6',['What is bytecode / NCG compilation?',['../index.html#autotoc_md171',1,'']]],
  ['neopixel_7',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md90',1,'']]],
  ['network_20reach_8',['Network Reach',['../index.html#autotoc_md42',1,'']]],
  ['new_20lisp_20primitives_9',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md18',1,'']]],
  ['nlambda_10',['nlambda',['../index.html#autotoc_md50',1,'']]],
  ['nlambda_20and_20macro_11',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['no_20call_20with_20current_20continuation_12',['Why no &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md178',1,'']]],
  ['no_20stop_20the_20world_20pauses_13',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md37',1,'']]],
  ['non_20blocking_20request_20poll_20model_14',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['non_20symbol_20keys_15',['Objects and non-symbol keys',['../index.html#autotoc_md56',1,'']]],
  ['not_20exceptions_16',['2.4 Events, Not Exceptions',['../index.html#profibus-events',1,'']]],
  ['not_20run_20on_20embedded_20hardware_17',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md30',1,'']]],
  ['not_20use_20embedded_20python_20derivatives_18',['Why not use embedded Python derivatives?',['../index.html#autotoc_md182',1,'']]],
  ['not_20use_20llvm_20for_20native_20code_20generation_19',['Why not use LLVM for native code generation?',['../index.html#autotoc_md184',1,'']]],
  ['notes_20',['Notes',['../index.html#modbus-platform',1,'4. Platform Notes'],['../index.html#fwd-arch-notes',1,'7. Architecture Notes']]],
  ['notes_20music_20scm_21',['Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)',['../index.html#autotoc_md116',1,'']]],
  ['now_22',['How do I try LambLisp right now?',['../index.html#autotoc_md156',1,'']]],
  ['numbers_23',['Numbers',['../index.html#autotoc_md129',1,'']]],
  ['numeric_20arrays_20array_24',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['numeric_20tower_25',['The Numeric Tower',['../index.html#autotoc_md127',1,'']]],
  ['nutshell_26',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md11',1,'']]],
  ['nvs_27',['The loader wire contract (NVS)',['../index.html#autotoc_md70',1,'']]]
];
