var searchData=
[
  ['embedded_20hardware_0',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md30',1,'']]],
  ['embedded_20i_20o_20esp32_20and_20compatible_1',['Arduino / Embedded I/O (ESP32 and compatible)',['../index.html#autotoc_md67',1,'']]],
  ['embedded_20python_20derivatives_2',['Why not use embedded Python derivatives?',['../index.html#autotoc_md182',1,'']]],
  ['environment_3',['Unified Distributed Environment',['../index.html#autotoc_md87',1,'']]],
  ['environment_20is_20a_20hierarchical_20dictionary_4',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['environment_20operations_5',['Dictionary (Environment) Operations',['../index.html#autotoc_md65',1,'']]],
  ['environments_20and_20evaluation_6',['Environments and Evaluation',['../index.html#autotoc_md145',1,'']]],
  ['error_20handling_7',['2.5 Error Handling',['../index.html#modbus-errors',1,'']]],
  ['error_20tags_8',['Error tags',['../index.html#autotoc_md112',1,'']]],
  ['esp32_9',['Deploy to ESP32',['../index.html#deploy-esp32',1,'']]],
  ['esp32_20and_20compatible_10',['Arduino / Embedded I/O (ESP32 and compatible)',['../index.html#autotoc_md67',1,'']]],
  ['esp32_20hardware_11',['ESP32 Hardware',['../index.html#autotoc_md5',1,'']]],
  ['esp32_20s3_12',['4.2 ESP32-S3',['../index.html#modbus-esp32',1,'']]],
  ['esp32_20s3_20eye_13',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['esp32_20system_14',['ESP32 System',['../index.html#autotoc_md105',1,'']]],
  ['eval_20operation_15',['The eval Operation',['../index.html#autotoc_md80',1,'']]],
  ['eval_20sandbox_20demo_20sandbox_20scm_16',['Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)',['../index.html#autotoc_md114',1,'']]],
  ['evaluation_17',['Environments and Evaluation',['../index.html#autotoc_md145',1,'']]],
  ['events_20not_20exceptions_18',['2.4 Events, Not Exceptions',['../index.html#profibus-events',1,'']]],
  ['example_19',['Example',['../index.html#fwd-run',1,'6. Running the Example'],['../index.html#fwd-extend',1,'7.3 Extending the Example'],['../index.html#autotoc_md72',1,'Example'],['../index.html#autotoc_md76',1,'Example']]],
  ['example_3a_20autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_20',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['example_3a_20supervisory_20control_20of_20the_20freenove_204wd_20car_21',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md85',1,'']]],
  ['examples_22',['Worked Examples',['../index.html#worked-examples',1,'']]],
  ['exception_20handling_23',['Exception Handling',['../index.html#autotoc_md153',1,'']]],
  ['exceptions_24',['2.4 Events, Not Exceptions',['../index.html#profibus-events',1,'']]],
  ['execution_20environment_20is_20a_20hierarchical_20dictionary_25',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['execution_20tiers_3a_20ast_20→_20bytecode_20→_20native_20code_26',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['existing_20c_20arduino_20libraries_27',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md16',1,'']]],
  ['exists_28',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['expander_20pcf8574_20scm_29',['I2C GPIO Expander (&lt;span class=&quot;tt&quot;&gt;PCF8574.scm&lt;/span&gt;)',['../index.html#autotoc_md99',1,'']]],
  ['extending_20the_20example_30',['7.3 Extending the Example',['../index.html#fwd-extend',1,'']]],
  ['extension_31',['C++ Extension',['../index.html#autotoc_md45',1,'']]],
  ['extensions_32',['Extensions',['../index.html#autotoc_md64',1,'LambLisp Extensions'],['../index.html#language-extensions',1,'Language Extensions']]],
  ['eye_33',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['eye_20cam_20scm_20live_20preview_20layer_34',['eye-cam.scm live-preview layer',['../index.html#autotoc_md93',1,'']]]
];
